### ISSUE TITLE
Select all checkbox not valid when scrollCollapse is enabled

### ISSUE THREAD

**Issue by Lingku** [gyrocode/jquery-datatables-checkboxes#1]
Select all checkbox will not valid when scrollCollapse is enabled
Following is an example:
  $('#example').DataTable({
    "scrollY":        "200px",
    "scrollCollapse": true,
    "paging":         false,
...
});

**Comment by mpryvkin** [comment]
Thanks for repporting, it has been fixed.

**Comment by Lingku** [comment]
It has been resolved, thanks a lot ;-)
