### ISSUE TITLE
issue using checkbox plugin along with responsive plugin

### ISSUE THREAD

**Issue by gkreddy** [gyrocode/jquery-datatables-checkboxes#10]
when we use responsive plugin (https://cdn.datatables.net/responsive/2.1.0/js/dataTables.responsive.min.js) both checkbox and responsive expland/collapse button appears in same column

**Comment by mpryvkin** [comment]
Thanks for reporting this issue. I see that the problem occurs when expand/collapse is clicked, checkbox and row get selected. However it's not an issue with the Checkboxes extension, but rather incompatibility of default settings between Responsive and Select extension. The workaround is to instruct Select extension not to select the row when first column is clicked by using special value `'td:not(:first-child)'` for  [`select.selector`](https://datatables.net/reference/option/select.selector) option.

For example:

    'select': {
         'style': 'multi',
         'selector': 'td:not(:first-child)'
     },

See [this example](https://jsfiddle.net/ffvxp3d0/) for code and demonstration.

**Comment by mpryvkin** [comment]
Also if you want the display expand/collapse control in a separate column, you can use [`responsive.details.target`](https://datatables.net/reference/option/responsive.details.target) option.

**Comment by mpryvkin** [comment]
Just published [jQuery DataTables - Responsive and Select extensions](http://www.gyrocode.com/articles/jquery-datatables-responsive-and-select-extensions/) article to demonstrate how to solve this problem.

**Comment by gkreddy** [comment]
I've changed target of responsive plugin to 1. when i click on expland row and checkbox will automatically select. please see the fiddle below

https://jsfiddle.net/ffvxp3d0/1/

**Comment by mpryvkin** [comment]
You need to update `select.selector` as well to exclude the second column.

See https://jsfiddle.net/ffvxp3d0/2/
