### ISSUE TITLE
Force number of selected row in the footer

### ISSUE THREAD

**Issue by swim89** [gyrocode/jquery-datatables-checkboxes#100]
Is there any way to force the show of number of selected row? Some piece of code that I can invoke?

**Comment by mpryvkin** [comment]
Can you please explain why do you need to do it?

**Comment by swim89** [comment]
I would to see the number of selected row in the footer, but for some problem of my code, it doesn't appear automatically as expected. So I would to force it...

**Comment by mpryvkin** [comment]
There is probably another reason for this. You need to solve the cause rather that battle with consequences ;). 

Please show your DataTables initialization code and data (HTML table or response in JSON format).

**Comment by swim89** [comment]
Thanks for your help!

Here my code: https://jsfiddle.net/swim89/2zLxfy1s/

**Comment by mpryvkin** [comment]
When I select a row or click on the checkbox "1 row selected" appears in the footer, which works as expected. 

If you want to select certain rows after loading the data, see [this example](https://www.gyrocode.com/projects/jquery-datatables-checkboxes/examples/api/select-checkboxes/).

**Comment by swim89** [comment]
I know that in the code I sent you, it works, but the same code, in my project doesn't work...and I don't know why :(

**Comment by mpryvkin** [comment]
Are you including Select extension? Please show what JS scripts are included in your project.

**Comment by swim89** [comment]
Here all my JS scripts included:

`<script src="http://et.loc:9080/plugins/bower_components/jquery/dist/jquery.min.js"></script>`
`<!-- Bootstrap Core JavaScript -->`
`<script src="http://et.loc:9080/bootstrap/dist/js/bootstrap.min.js"></script>`
`<!-- Stylish Tabs/Tooltips -->`
`<script src="http://et.loc:9080/js/cbpFWTabs.js"></script>`
`<!--BlockUI Script -->`
`<script src="http://et.loc:9080/plugins/bower_components/blockUI/jquery.blockUI.js"></script>`
`<!--Morris JavaScript -->`
`<script src="http://et.loc:9080/plugins/bower_components/raphael/raphael-min.js"></script>`
`<script src="http://et.loc:9080/plugins/bower_components/morrisjs/morris.js"></script>`
`<script src="http://et.loc:9080/plugins/bower_components/knob/jquery.knob.js"></script>`

`<script src="http://et.loc:9080/plugins/bower_components/waypoints/lib/jquery.waypoints.js"></script>`
`<script src="http://et.loc:9080/plugins/bower_components/counterup/jquery.counterup.min.js"></script>`

`<!--Datatables -->`
`<script src="http://et.loc:9080/plugins/bower_components/datatables/media/js/jquery.dataTables.min.js"></script>`
`<script src="http://et.loc:9080/plugins/bower_components/jquery-datatables-checkboxes/js/dataTables.checkboxes.min.js"></script>`
`<script src="https://cdn.datatables.net/buttons/1.5.6/js/dataTables.buttons.min.js"></script>`


`<script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.4/lodash.min.js"></script>`

`<!-- Menu Plugin JavaScript -->`
`<script src="http://et.loc:9080/plugins/bower_components/sidebar-nav/dist/sidebar-nav.min.js"></script>`
`<!-- Slimscroll JavaScript -->`
`<script src="http://et.loc:9080/js/jquery.slimscroll.js"></script>`
`<!-- Wave Effects -->`
`<script src="http://et.loc:9080/js/waves.js"></script>`
`<!-- Custom Theme JavaScript -->`
`<script src="http://et.loc:9080/js/custom.js"></script>`
`<script src="http://et.loc:9080/custom/js/custom.js"></script>`
`<!-- Style Switcher -->`
`<script src="http://et.loc:9080/plugins/bower_components/styleswitcher/jQuery.style.switcher.js"></script>`
`<!-- Moment JS -->`
`<script src="http://et.loc:9080/plugins/bower_components/moment/moment.js"></script>`
`<!-- Bootstrap Datepicker -->`
`<script src="http://et.loc:9080/plugins/bower_components/bootstrap-datepicker/bootstrap-datepicker.min.js" type="text/javascript"></script>`
`<!-- Bootstrap Datepicker: Italian -->`
`<script src="http://et.loc:9080/plugins/bower_components/bootstrap-datepicker/locales/bootstrap-datepicker.it.min.js" type="text/javascript"></script>`
`<!-- Bootstrap Daterangepicker -->`
`<script src="http://et.loc:9080/plugins/bower_components/bootstrap-daterangepicker/daterangepicker.js" type="text/javascript"></script>`
`<!-- Bootstrap Select -->`
`<script src="http://et.loc:9080/plugins/bower_components/select2/js/select2.min.js" type="text/javascript"></script>`
`<script src="http://et.loc:9080/plugins/bower_components/bootstrap-select/bootstrap-select.min.js" type="text/javascript"></script>`
`<!-- Bootstrap Typehead -->`
`<script src="http://et.loc:9080/plugins/bower_components/typeahead.js-master/dist/typeahead.bundle.min.js" type="text/javascript"></script>`
`<!-- Sweet Alert -->`
`<script src="http://et.loc:9080/plugins/bower_components/sweetalert/sweetalert.min.js" type="text/javascript"></script>`
`<script src="http://et.loc:9080/plugins/bower_components/sweetalert/jquery.sweet-alert.custom.js" type="text/javascript"></script>`
`<!-- Notifications -->`
`<script src="http://et.loc:9080/plugins/bower_components/toast-master/js/jquery.toast.js"></script>`
`<script src="http://et.loc:9080/js/toastr.js"></script>`
`<!--Nestable js -->`
`<script src="http://et.loc:9080/plugins/bower_components/nestable/jquery.nestable.js"></script>`
`<!-- Boostrap Switch -->`
`<script src="http://et.loc:9080/plugins/bower_components/switchery/dist/switchery.min.js"></script>`
`<!-- Numeric Input -->`
`<script src="http://et.loc:9080/plugins/bower_components/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.min.js" type="text/javascript"></script>`
`<!-- Bootstrap Multi-select -->`
`<script src="http://et.loc:9080/plugins/bower_components/multiselect/js/jquery.multi-select.js" type="text/javascript"></script>`
`<!-- Dropify -->`
`<script src="http://et.loc:9080/plugins/bower_components/dropify/dist/js/dropify.js" type="text/javascript"></script>`
`<!-- Form Mask -->`
`<script src="http://et.loc:9080/js/inputmask.js"></script>`
`<!-- ICheck -->`
`<script src="http://et.loc:9080/plugins/bower_components/icheck/icheck.min.js"></script>`
`<script src="http://et.loc:9080/plugins/bower_components/icheck/icheck.init.js"></script>`
`<!-- Form Wizard JavaScript -->`
`<script src="http://et.loc:9080/plugins/bower_components/jquery-wizard-master/dist/jquery-wizard.min.js"></script>`
`<!-- Bootstrap Table -->`
`<script src="http://et.loc:9080/plugins/bower_components/bootstrap-table/dist/bootstrap-table.min.js"></script>`
`<script src="http://et.loc:9080/plugins/bower_components/bootstrap-table/dist/bootstrap-table.ints.js"></script>`
`<!-- Image cropper JavaScript -->`
`<script src="http://et.loc:9080/plugins/bower_components/cropper/cropper.min.js"></script>`
`<!-- Clock Plugin JavaScript -->`
`<script src="http://et.loc:9080/plugins/bower_components/clockpicker/dist/jquery-clockpicker.min.js"></script>`
`<!-- EASY PIE CHART JS -->`
`<script src="http://et.loc:9080/plugins/bower_components/jquery.easy-pie-chart/dist/jquery.easypiechart.min.js"></script>`
`<script src="http://et.loc:9080/plugins/bower_components/jquery.easy-pie-chart/easy-pie-chart.init.js"></script>`

**Comment by mpryvkin** [comment]
You don't have [Select](https://datatables.net/extensions/select/) extension included, that is why you have no row selection functionality including the info in the footer.

**Comment by swim89** [comment]
@mpryvkin Thanks but it’s still not working...

**Comment by mpryvkin** [comment]
File `dataTables.select.min.js` must be included after `jquery.dataTables.min.js`. Make sure that all components are actually loading and not producing 404 error.

If that doesn't work try replacing `jquery.dataTables.min.js` and `dataTables.select.min.js` with this script `https://cdn.datatables.net/v/dt/dt-1.10.18/sl-1.3.0/datatables.min.js`

**Comment by swim89** [comment]
Yep! Replacing `jquery.dataTables.min.js` and `dataTables.select.min.js` with the CDN files, it works! Thanks :)

**Comment by mpryvkin** [comment]
Don't forget to use corresponding CSS file from CDN as well instead of the ones you use now.

**Comment by swim89** [comment]
Yes! But is it possible to change the language? Because I'm using `//cdn.datatables.net/plug-ins/1.10.19/i18n/Italian.json` but the only part of code not translated is the number of selected rows.

**Comment by mpryvkin** [comment]
Please see [Localization](https://www.gyrocode.com/projects/jquery-datatables-checkboxes/examples/basic/localization/) example.

**Comment by swim89** [comment]
Top! Thanks again :)
