### ISSUE TITLE
How to disable few rows for selection?

### ISSUE THREAD

**Issue by leeoo** [gyrocode/jquery-datatables-checkboxes#101]
Like below question described:
https://stackoverflow.com/questions/44201271/datatables-select-disable-few-rows-for-selection

My scenario: Show only check boxes for the rows whose status is fail.
```
[ ]     id     taskName    status
--------------------------------------------------
        1      task1        success
[ ]     2      task2        fail
        3      task3        success
        4      task4        success
[ ]     5      task5        fail
--------------------------------------------------
[Submit selected fail task(s) for rerun]
```

**Comment by mpryvkin** [comment]
Please see [Disable checkboxes on page load](https://www.gyrocode.com/projects/jquery-datatables-checkboxes/examples/api/disable-checkboxes/) or [this extended example](https://jsfiddle.net/gyrocode/grnatp23/).

**Comment by leeoo** [comment]
Thank you very much!
