### ISSUE TITLE
Disabling checkboxes on page load with HTML sourced data not working

### ISSUE THREAD

**Issue by Blimie** [gyrocode/jquery-datatables-checkboxes#104]
Example with alternative solution for html sourced data (https://www.gyrocode.com/projects/jquery-datatables-checkboxes/examples/api/disable-checkboxes/#solution2) doesn't work for me. Even the checkboxes that are not grayed out are disabled. 
Can you please show a working example of disabling checkboxes with html sourced data? Thank You!

**Comment by mpryvkin** [comment]
I updated [Disable checkboxes on page load](https://www.gyrocode.com/projects/jquery-datatables-checkboxes/examples/api/disable-checkboxes/) page adding an example on jsFiddle for alternative solution with HTML-sourced data.

**Comment by Blimie** [comment]
works great! thanks a lot Michael
