### ISSUE TITLE
RowsCount even if selectRow is false

### ISSUE THREAD

**Issue by swim89** [gyrocode/jquery-datatables-checkboxes#105]
If the value of `selectRow` is false and you click on the row (but don't check it) the `rowsCount` add/remove element on the footer.

**Comment by mpryvkin** [comment]
This is correct behavior, see [this example](https://jsfiddle.net/tewajk3b/). 

If you set `selectRow: false` , footer counter shows number of selected rows, and not number of rows with checked boxes.

**Comment by swim89** [comment]
Thank you for your answer! Is there any way to disable RowsCount if the checkbox is not checked?

**Comment by mpryvkin** [comment]
Yes, you can use [`select.info()`](https://datatables.net/reference/api/select.info()) Select extension API method to disable info about selected rows. See [this example](https://jsfiddle.net/3ob4ta1p/).

But it doesn't make sense to me why would you want to hide number of selected rows and keep the ability to select rows.

**Comment by swim89** [comment]
I want to select the rows by checking the checkbox not clicking on the row. This is my sense..

**Comment by mpryvkin** [comment]
Best solution to prevent row selection by clicking on the row is to limit selection to the column containing checkboxes by using [`select.selector`](https://datatables.net/reference/option/select.selector) option.

```
'select': {
   'style': 'multi',
   'selector': 'td:first-child'
},
```

See [this example](https://jsfiddle.net/c10bn2zj/1/) for code and demonstration. 

You can combine it with using `select.info()` API method to disable info about selected rows if you want.
