### ISSUE TITLE
[Questions] how to add / pass a value

### ISSUE THREAD

**Issue by lenamtl** [gyrocode/jquery-datatables-checkboxes#106]
Hi

I need to add a checkbox so user can delete multiple items.
I'm actually do it manually and try to do it using the checkbox plugin

1- This plugin is 2 years old, is this plugin still active or Datatables Select does the same thing now ?

2- I'm wondering how can I set a value to the checkbox 
Let say a user select a few checkbox and click on submit button I need the $item_id of each selected row to be sent  to my Ajax, as the checkbox is populated by the script how can we set a value for each line/ row?  Note this value is hidden value not visible on the table.

I actually do it manually like this

```
<td><input type='checkbox' class='delete_check'  value='<?php echo $item_id; ?>' ></td>

            $('#checkall').click(function(){
                if($(this).is(':checked')){
                    $('.delete_check').prop('checked', true);
                }else{
                    $('.delete_check').prop('checked', false);
                }
            });


            $('#delete_record').click(function(){

                var deleteids_arr = [];
               
                $("input:checkbox[class=delete_check]:checked").each(function () {
                    deleteids_arr.push($(this).val());
                });
                
              
                if(deleteids_arr.length > 0){

                
                    var confirmdelete = confirm("Do you really want to Delete records?");
                    if (confirmdelete == true) {
                        /* $.ajax({
                            url: 'ajaxfile.php',
                            type: 'post',
                            data: {request: 2,deleteids_arr: deleteids_arr},
                            success: function(response){
                                dataTable.ajax.reload();
                            }
                        });
						*/
						alert(deleteids_arr);
                    } 
                }
            });

```
Thanks

**Comment by lenamtl** [comment]
I have not found any way to pass a value ti the checkbox.
I'm not a fan to have a table into a form 

Till now the only solution is to have my $item_id into an hidden column (which I would prefer not to have)
And use pluck() and toArray() APIs to get the data

Something like this
```
function () {
                    var data = table.rows( { selected: true } ).data().pluck(0).toArray();
                    // post the value
                    //events.prepend( '<div>'+data+'</div>' );
                }
```


Let me know if you have other solutions.
Thanks

**Comment by mpryvkin** [comment]
I am not actively working on the plug-in but I fix bugs and add features on-demand when deemed necessary.

You can submit data via Ajax if you don't want to submit the entire form. See example shown on the main page as a starting point.

When user presses "Delete" button, handle click event and perform the following.

1. Retrieve selected data using `checkboxes.selected()` API method, for example.
    ```
    var rows_selected = table.column(0).checkboxes.selected().toArray();
    ```
2. Send Ajax request to your server-side script.
    ```
    $.ajax({
       url: '/path/to/your/script'
       method: 'POST',
       data: {
          id: rows_selected
       }
    })
    .done(function(data){
       // Reload table data
 
       // If data is HTML sourced, use
       // window.location.reload(true);

       // If data is Ajax-sourced, use 
       // table.ajax.reload()
    });
   ```

**Comment by lenamtl** [comment]
Thanks

**Comment by lenamtl** [comment]
Notes:

I encounter a problem with my solution and I want to prevent other user about the problem:
`var data = table.rows( { selected: true } ).data().pluck(2).toArray();`

There is a problem because if the column get reordered the value is no more accurate, this is a big problem.
A quick fix was preventing the column to get reordered.
```
"colReorder": {
		fixedColumnsLeft:3,
	},
```

But a found a more reliable solution that I want to share:

I set a name to the column in column Defs where I want to retrieve the information 
```
"columnDefs": [								  
        {	
             {
		targets: 2,
        	name: 'myid'
          }																
	],

```

Then I get the column index ID and checked the selected values.
Here is an example using a click of a button to simply the example
```
 $('#getids').click(function () {   	
         var myindex = table1.column('myid:name').index();
         var selectedid = table1.rows( { selected: true } ).data().pluck(myindex).toArray();
         console.log(selectedid);
}
```

*Now I can reorder the column with no problem this always give me the correct value.

@mpryvkin I could not get the data based on your var rows_selected solution...
