### ISSUE TITLE
[Bug] the script bypass the Datatables Select Info settings 

### ISSUE THREAD

**Issue by lenamtl** [gyrocode/jquery-datatables-checkboxes#110]
Hi,

I'm using Datatables Select with jquery-datatables-checkboxes
I edited datatables select plugin so info default value is false (because I don't use it much)
`var info = false;`

and I have also tried this instead of editing the select JS file
to set default value

```
$.extend( $.fn.dataTable.defaults, {
                 "select": {
            	"info": false,
                 },
            });
```

This working fine the info does not appear on my tables except it appear on the table where I use jquery-datatables-checkboxes plugin which is fine but I did not enable it yet ????
```
"select": {
	'style': 'multi',
	'selector': 'td:nth-child(2),td:nth-child(10)',
	//'info': true,
},
```

So this mean that jquery-datatables-checkboxes  enable to display info by default and bypassed the Datatables Select settings
It is ok this is what i need for now but that will be great so it can also be turn off using the Select setting to be more uniform.

If there is way to turn it off in case I need it later I would like to know how

Thanks

**Comment by mpryvkin** [comment]
Thanks for reporting. Yes, I agree that plug-in need to respect [`select.info`](https://datatables.net/reference/option/select.info) option by default.

**Comment by lenamtl** [comment]
I have tested and this is fixed ok.
Thanks
