### ISSUE TITLE
Uncaught TypeError: Cannot read property 'register' of undefined

### ISSUE THREAD

**Issue by ikramooe** [gyrocode/jquery-datatables-checkboxes#111]
i keep getting this error Uncaught TypeError: Cannot read property 'register' of undefined at checkbox.min.js  

and the checkboxes aren't showing

**Comment by lenamtl** [comment]
Hi,

Check the order of your Javascript files and make sure you have all the required Javascript files

**Comment by mpryvkin** [comment]
Yes, @lenamtl is correct. Most likely the issue is that you're including checkbox plugin **BEFORE** jQuery and/or jQuery DataTables files. It needs to be included **AFTER** jQuery and jQuery DataTables CSS/JS files.
