### ISSUE TITLE
DataTables button not showing when using this plugin

### ISSUE THREAD

**Issue by kcastro18** [gyrocode/jquery-datatables-checkboxes#113]
The plugin seems to have conflict with datatable buttons.

I've been trying to figure why the excel export button on my datatable is not showing and I tried changing the buttons to other ones like pdf or copy and non of then were showing. I did a lot of troubleshooting to figure out one is wrong, my datatable codes looks correct and everything else are working. So then I thought of maybe this plugin is causing the buttons not show up so I tried removing it and sure enough the buttons showed up.

I hope this get fixed. I really like this plugin and I'm hoping I can continue using this without it causing problems. 

If you have suggestion for a workaround I will greatly appreciate it.

Thank you.

**Comment by mpryvkin** [comment]
Can you please show your DataTables initialization options?

**Comment by kcastro18** [comment]
var table = $('#tblData').DataTable({
                "ajax": {
                    "url": "SomeURL",                    
                },
                "columnDefs": [
                    {
                        "targets": 0,
                        "checkboxes": {
                            'selectRow': true,
                            'selectAllPages': false,
                            'selectAllRender': '<input name="select_all" type="checkbox">'
                        }
                    },
                    { "targets": [5, 6, 7, 8, 9], "visible": false },
                    { "targets": 1, "width": "15%" }
                ],
                order: [[1, "asc"]],
                destroy: true,
                dom: 'Bfrtip',                                
                buttons: [        
                    {                        
                        extend: 'excelHtml5',
                        title: 'All Data'
                    }                    
                ],                                                        
            });

**Comment by mpryvkin** [comment]
Sorry, I could not replicate the issue. Please see [Buttons extension example with default options](https://jsfiddle.net/gyrocode/yehtaczj/) and [example with options similar to yours](https://jsfiddle.net/2ryk0jcs/). Are you able to demonstrate the problem using one of these examples as a starting point?

**Comment by kcastro18** [comment]
Hi,

I did copy the code with the default options and the buttons are still not showing(refer to the image below). I even use the sample data on your example to make sure it is exactly the same. My whole project also use     jquery.dataTables.js and dataTables.bootstrap.js, do you think that matters? 

Please let me know.

Thank you!

![image](https://user-images.githubusercontent.com/15161975/75793690-580b3200-5d35-11ea-8ee6-d3fea7f64589.png)

**Comment by lenamtl** [comment]
Hi,

Which Datatables version are you using?
I saw an issue about buttons recently.

If you right click / inspect using Chrome do you have any JS error into the console?

Also make sure you have all button scripts and CSS url / link loaded.
The links order are important too and must be after datatables.js one.

I'm using Datatables with Bootstrap with no problem.

To investigate I would do a basic table without ajax and check if this is working ok then I would make a more complex table using Ajax ...
