### ISSUE TITLE
Disable Checkboxes Based On Column Data - Rowgroup

### ISSUE THREAD

**Issue by Blimie** [gyrocode/jquery-datatables-checkboxes#115]
Hi,

First and foremost - this plugin is great!

My question is how I can disable checkboxes based on column data. I'm using HTML-sourced data. 
I used this https://www.gyrocode.com/projects/jquery-datatables-checkboxes/examples/api/disable-checkboxes/ for a page where I didn't need rowgroup and it worked. But now I'm rowgrouping following your code here: https://www.gyrocode.com/projects/jquery-datatables-checkboxes/examples/integration/rowgroup/ and I can't seem to make some checkboxes disabled. 

Thanks in advance!

**Comment by lenamtl** [comment]
Hi,

I'm curious for which condition the checkbox should be disabled?

**Comment by mpryvkin** [comment]
Sorry for the late reply. See [this example](https://jsfiddle.net/gyrocode/ow20c864/) for code and demonstration. I also added this example to the [RowGroup](https://www.gyrocode.com/projects/jquery-datatables-checkboxes/examples/integration/rowgroup/) page as well.

**Comment by Blimie** [comment]
Thanks Michael!
Your example is exactly what I was looking for. 
Your jsfiddle works. Somehow when I copy your code it doesn't work for me. 
The checkboxes aren't rendered (so 'render' works) but the row isn't disabled (which means 'createdCell' doesn't work properly). 
Does it make a difference that my data is HTML-sourced?

**Comment by mpryvkin** [comment]
That is correct, for HTML-sourced data there is a different approach. See [this example](https://jsfiddle.net/gyrocode/7fecwqh6/) for HTML-sourced data.

**Comment by Blimie** [comment]
Thanks Michael,
After tweaking the code a little that worked for me!
For some odd reason `data[2]` didn't work. I had to do `data.Position`

Thanks again!
