### ISSUE TITLE
Strange issue

### ISSUE THREAD

**Issue by lenamtl** [gyrocode/jquery-datatables-checkboxes#116]
Hi,

I have a big issue...
If I select  checkboxes and refresh the page = the checkboxes get deselected = OK

If  I select checkboxes and go to another the page, and click back from the browser 
= the checkboxes are still selected = Not OK 

I have checked my localstorage and there are no localstorage for the Selection...
So how come these are still selected?
If I refresh the page there are no more selected checkbox, I'm pulling my hair with this, any clue?

Here is my Datatables settings
```
"stateSave": true,
{									
				
	"targets": 1,
	"visible": true,
	"searchable": false,
	"orderable": false,
	"checkboxes": {
			"selectRow": true,
			"stateSave": false, 
        }
},

"select": {
	'style': 'multi',
	'selector': 'td:nth-child(2)',
},
```

**Comment by mpryvkin** [comment]
Can you provide an URL or an example demonstrating the issue?

**Comment by lenamtl** [comment]
You will be able to reproduce it on any webpage that have these settings

```
"stateSave": true,
{									
				
	"targets": 1,
	"visible": true,
	"searchable": false,
	"orderable": false,
	"checkboxes": {
			"selectRow": true,
			"stateSave": false, 
        }
},

"select": {
	'style': 'multi',
	'selector': 'td:nth-child(2)',
},
```

 just load the page select one or more item using the checkbox
change page (let say I'm clicking on menu item) then hit the back button from browser
the items are still selected and should not.

It's look likeusing the browser back button will not refresh the page, so by using this JS code it force to refresh the page 
```
if(performance.navigation.type == 2){
location.reload(true);
}
```

**Comment by lenamtl** [comment]
Hi,

I have recreated the case here https://jsfiddle.net/lenamtl/fzr46ut9/

Select All or a few checkboxes
Then click on the link Visit W3Schools
Then click on back browser buttons
= the checkboxes are still checked

**Comment by lenamtl** [comment]
After investigations, it was an autocomplete issue 
like we often see in a form but I didn't thought that could happens to a table :)

Here is the code fix:

```
initComplete: function (row) {
    $('th.dt-checkboxes-cell').find('input').attr('autocomplete', 'off');
    $('th.dt-checkboxes-select-all').find('input').attr('autocomplete', 'off');
    $('.dt-checkboxes').attr('autocomplete', 'off');
    },
```

**Comment by mpryvkin** [comment]
Thanks for the follow-up and showing the workaround! I might add `autocomplete="off"` attribute to the checkbox HTML code. However need to research this further.

From [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete) page
> Note: The `autocomplete` attribute also controls whether Firefox will — unlike other browsers — [persist the dynamic disabled state and (if applicable) dynamic checkedness](https://stackoverflow.com/questions/5985839/bug-with-firefox-disabled-attribute-of-input-not-resetting-when-refreshing) of an `<input>` element, `<textarea>` element, or entire `<form>` across page loads. The persistence feature is enabled by default. Setting the value of the `autocomplete` attribute to `off` disables this feature. This works even when the `autocomplete` attribute would normally not apply by virtue of its type. See [bug 654072](https://bugzilla.mozilla.org/show_bug.cgi?id=654072).

**Comment by lenamtl** [comment]
To what I have read putting autocomplete="off" to a form tag will work better, butin our case it's not a form, so I don't know how reliable it is

Forcing the code refresh based on browser historic is another alternative but we can see the checkboxed checked then uncheck (this is fast but we can see it) .

**Comment by lenamtl** [comment]
To fix it directly into your plugin code 
Let me know if this is ok

```
if(ctx.aoColumns[i].mRender === null){
                  colOptions['render'] = function(){
                     //return '<input type="checkbox" class="dt-checkboxes">';
		       return '<input type="checkbox" class="dt-checkboxes" autocomplete="off">';
                  };
               }
 //selectAllRender: '<input type="checkbox">'
selectAllRender: '<input type="checkbox" autocomplete="off">'
```

**Comment by mpryvkin** [comment]
That seems safe, I will apply the change later today.
