### ISSUE TITLE
Bootstrap Custom Checkboxes support

### ISSUE THREAD

**Issue by HaroonKhalid824** [gyrocode/jquery-datatables-checkboxes#117]
It's a great plugin. I used it in a project where Bootstrap's custom checkboxes were used. But this project comes with native checkboxes. So I changed the source according to my needs and used it in my project. I want to contribute this change to this open-source plugin. Please tell me how can I contribute
![Screen Shot 2020-05-05 at 3 27 57 PM](https://user-images.githubusercontent.com/20097802/81057025-176e9700-8ee5-11ea-9e7f-5742145c947b.png)
. I've forked and clones the project but there isn't any contribution guide included. Thank you.

**Comment by mpryvkin** [comment]
I don't see any commits to your forked repo. However I suspect that no PR would be necessary because the plug-in was designed to be customizable out of the box, see [Styling](https://www.gyrocode.com/projects/jquery-datatables-checkboxes/examples/styling/) examples.

**Comment by HaroonKhalid824** [comment]
I saw the styling example. The difference between native checkboxes and bootstrap custom checkboxes is that they differ in html structure. But I see we can use rendering methods explained in the style guide to achieve desired results. Thanks for getting back.
