### ISSUE TITLE
[question] about latest release 

### ISSUE THREAD

**Issue by lenamtl** [gyrocode/jquery-datatables-checkboxes#118]
Hi,

Could you explain which bug the latest release fix 
https://github.com/gyrocode/jquery-datatables-checkboxes/commit/c684be393dc2536a3327297390f64e42fdeb8fbf

I would like to test it prior updating could you explain how to reproduce the bug.
Is this related to a specific issue number
Thanks

**Comment by mpryvkin** [comment]
It was an issue reported to me via email some time ago. 

Please see [this example](https://jsfiddle.net/0bz4jqk1/1/), click on "Select All" checkbox and inspect the console. Data will be related to previous selection and not the current one.
