### ISSUE TITLE
Documentation: columns.checkboxes.selectRow appears twice in the 'details' section

### ISSUE THREAD

**Issue by matthewhegarty** [gyrocode/jquery-datatables-checkboxes#120]
- Load the [documentation](https://www.gyrocode.com/projects/jquery-datatables-checkboxes/reference/options/#columns.checkboxes.selectRow) page, and scroll to the 'Details' section.

- The option for 'selectRow' is listed twice.   

![cb1](https://user-images.githubusercontent.com/6249838/89945990-210d4680-dc1a-11ea-8f29-a98441233a34.png)

**Comment by mpryvkin** [comment]
Thanks for reporting, it's been fixed.
