### ISSUE TITLE
Error hasOwnProperty on DataTable checkboxes

### ISSUE THREAD

**Issue by ssukang** [gyrocode/jquery-datatables-checkboxes#121]
I'm trying to use DataTable checkboxes feature, but as of now the selection is running into these following errors: 

`
Uncaught TypeError: Cannot read property 'hasOwnProperty' of undefined at dataTables.checkboxes.js:674
`

`
Uncaught TypeError: Cannot read property 'hasOwnProperty' of undefined
    at x.isCellSelectable (dataTables.checkboxes.js:887)
    at x.onDataTablesUserSelect (dataTables.checkboxes.js:383)
    at HTMLTableElement.<anonymous> (dataTables.checkboxes.js:247)
    at HTMLTableElement.dispatch (vendor_scripts.js:5569)
    at HTMLTableElement.elemData.handle (vendor_scripts.js:5373)
    at Object.trigger (vendor_scripts.js:8855)
    at HTMLTableElement.<anonymous> (vendor_scripts.js:8933)
    at Function.each (vendor_scripts.js:521)
    at jQuery.fn.init.each (vendor_scripts.js:343)
    at jQuery.fn.init.trigger (vendor_scripts.js:8932)
`

It seems like there are bunch of undefined getting caught in dataTables.checkboxes.js. The data in console.log successfully report change when I click other data, but these error asOwnProperty on DataTable checkboxes come up and thus block the selection and color change. I've seen other reporting the same issue here https://stackoverflow.com/questions/49527455/error-hasownproperty-on-datatable-checkboxes 

Would appreciate getting fix / advice as soon as possible!

**Comment by mpryvkin** [comment]
Can you please provide reproducible example on jsFiddle.net using [this example](https://jsfiddle.net/gyrocode/snqw56dw/) as a start? If you could share your DataTables initialization code, that would be appreciated as well. Thanks!

**Comment by ssukang** [comment]
I tried reproducing my example in JSFiddle, but couldn't get ReactDOM working. 
Ultimately, I'm trying to achieve checkbox in my table & communicating selected data from child component to parent component. 
Here is my code (jQuery configured in webpack.config.js): 

HTML: 
```html
{% block includes %}
    {{ super() }}

    <script src="https://d3js.org/d3-dsv.v1.min.js"></script>
    <script src="{{ url_for('static', filename='js/lib/observable.js') }}"></script>

{% endblock %}

{% block css %}
    {{ super() }}
    <link type="text/css" href="//gyrocode.github.io/jquery-datatables-checkboxes/1.2.12/css/dataTables.checkboxes.css" rel="stylesheet" />
    <script type="text/javascript" src="//gyrocode.github.io/jquery-datatables-checkboxes/1.2.12/js/dataTables.checkboxes.min.js"></script>
{% endblock %}

<div className="row">
    <div id="my-table-view">
        <div className="col-md-12">
            <div id="my-dt-title-root"></div>
            <table id="my-dt-root" width="100%"></table>
        </div>
    </div>
</div>

<script src="{{ url_for('static', filename='jmy_table_script.bundle.js') }}" defer></script>
```

index.js:
```js
import React from "react";
import ReactDOM from "react-dom";
import Table from "./components/table";

$(document).ready(function () {
    ReactDOM.render(
        <Table
            identifier_1={{
                "id": baid
            }}
        />,
        document.getElementById("my-dt-title-root")
    );
});
```

components/table.js:
```js
import React from "react";
import ReactDOM from "react-dom";

export class PlateMapSummaryTable extends React.Component {
    constructor(props) {
        super(props);
        this.onSelect = this.onSelect.bind(this);
    }

    onSelect(selected) {
        console.log('on select');
    }

   render() {
    var dt_data = **_function gets data based on this.props.identifier.id_**
    var table = $(tName).DataTable({
        destroy: true,
        pageLength: 10, 
        lengthMenu: [[10, 25, 50, -1], [10, 25, 50, "All"]],
        processing: true,
        data: dt_data,
        select: {
            style: 'multi'
        },
        columns: dt_columns,
        columnDefs: [
            {
                targets: 0,
                checkboxes: { selectRow: true }
            }]

    }).draw();

    let t_selected = [];
    let handler = this.onSelect;
   
        table
            .on( 'user-select', function ( e, dt, type, cell, originalEvent ) {
                console.log('caught select event');
                let s = cell[0][0].row;
                if (!t_selected.includes(s)) {
                    t_selected.push(s);
                } else {
                    t_selected = t_selected.filter(elem => elem != s);
                }
                handler(t_selected);
            } );
  }


 return (
      <h2>Plate Summary</h2>
 );

}

```

**Comment by ssukang** [comment]
Apologies for the uneven spacing, but I hope you get the idea of what I'm going for.

**Comment by mpryvkin** [comment]
So far I cannot reproduce this issue. When does the error in the console occur - on page load or as a result of selection?

Couple odd things in your code:

1. Remove uneccessary `.draw()` call.

2. Detach `user-select` event handler before attaching:

    ```
    table.off('user-select');
    table.on('user-select', function ( e, dt, type, cell, originalEvent ) {
       // ... skipped ...
    });
    ```

**Comment by mpryvkin** [comment]
I suspect the issue is in some unexpected use of the plug-in. I pushed this commit (5a6987e7772d032504dfce253116ac30251d06e0), please see if it at least makes the error to go away.
