### ISSUE TITLE
'Indeterminate' checkbox state

### ISSUE THREAD

**Issue by Jollus174** [gyrocode/jquery-datatables-checkboxes#123]
I have a demo of the 'Indeterminate' checkbox in the top-left being buggy in this demo: https://codepen.io/joel-sweetman/pen/GRZMqjY

- The first example is a dataTable initalised through an existing table (this is where the buggy indeterminate checkbox state occurs).
- The second is through JSON data passed into it (the indeterminate state here works as expected).

I'm about to do a fork and investigate further, but I believe the issue is occurring here in the code:
```
	$.each(cellsData, function(index, cellData){
		// If checkbox is not disabled
               if(self.isCellSelectable(colIdx, cellData)){
                  if(
                     Object.prototype.hasOwnProperty.call(self.s.data, colIdx)
                     && Object.prototype.hasOwnProperty.call(self.s.data[colIdx], cellData)
                     ) {
                     countChecked++;
                  }

               // Otherwise, if checkbox is disabled
               } else {
                  countDisabled++;
               }
            });
```
It looks like `countChecked` is not counting correctly in the first demo, which will cause the indeterminate checkbox state for selectAll to not be toggled.

**Comment by mpryvkin** [comment]
Thanks for reporting the issue and example, let me look into this.

**Comment by mpryvkin** [comment]
The problem is that in the HTML-sourced table IDs were missing from the first column. Currently it's the limitation of the plug-in which requires for column with checkboxes to have unique values. 

There was also missing CSS stylesheet for the plug-in, however this is not related to the issue.

See [updated example](https://codepen.io/gyrocode/pen/yLOzXON) where it works as expected.

**Comment by Jollus174** [comment]
Ah, amazing! The issue was with my JS Checkboxes markup. Thanks very much for your help!
