### ISSUE TITLE
selectAll callback issue 

### ISSUE THREAD

**Issue by nonoantog** [gyrocode/jquery-datatables-checkboxes#126]
HI, 

I want to do some stuff when the user selects the checkbox in the header.

But, every time I check a row in the table body, it is calling to selectCallBack and it is calling selectAllCallback callback. 

So.. is there a way to identify that the callback is from the header and not from the body row?

1) select a row in the body  => callbacks called,  select,selectAll 
2) select from header check => callbacks called, selectAll

I know this is a question, not an issue. It should be tagged as questions.

Thanks.

**Comment by mpryvkin** [comment]
There is [`selectAllCallback`](https://www.gyrocode.com/projects/jquery-datatables-checkboxes/reference/options/#columns.checkboxes.selectAllCallback) option that allows you to define a function which will be called when "Select all" control in the header is clicked. Please see sample function provided by @vonDassendorf .

**Comment by Jequex** [comment]
Clicking the checkbox on a row calls both functions => selectCallback and selectAllCallback likewise clicking on the select all checkbox. Is there a way around  this?
