### ISSUE TITLE
Get data of selected row

### ISSUE THREAD

**Issue by sebastianro92** [gyrocode/jquery-datatables-checkboxes#127]
Hi, is there any way, to get the data of the selected row using server side?

**Comment by nikitul** [comment]
Yes. The best way to do it is to set up a repo and using ```selectCallback``` to capture the selected/deselected cellNodes, and with them, find the selected row and save/delete it from repo. I made a [fiddle](https://jsfiddle.net/qogbpj16/5/) for it.
