### ISSUE TITLE
No of rows always shows '1 row(s) selected' when data for table is HTML DOM sourced

### ISSUE THREAD

**Issue by niyasmo** [gyrocode/jquery-datatables-checkboxes#129]
I'm using HTML DOM sourced data and trying to get the list of rows selected in the table. But unfortunately even we select multiple rows it shows 1 rows selected

**Comment by mpryvkin** [comment]
Most likely the problem is that in the HTML-sourced table IDs are missing from the column containing checkboxes. Currently it's the limitation of the plug-in which requires for column with checkboxes to have unique values.
