### ISSUE TITLE
fixedColumns

### ISSUE THREAD

**Issue by s0By** [gyrocode/jquery-datatables-checkboxes#13]
Hi there! 

Sorry, but another complication for you. 
When using checkboxes with fixedColumns the solution doesn't work anymore, because elements are getting duplicated and element issues occur. 

If you click on elements, you still get the selected count, but select all doesn't work anymore, because the element that gets updated is actually "behind" the duplicated one. 

[Fiddle](https://jsfiddle.net/d5Ld0x7n/1/)

Regards

**Comment by mpryvkin** [comment]
Thanks for providing the example. These two extensions are clearly incompatible. Let me take some time to see if I can provide support for FixedColumns extension.

**Comment by charlesshenxc** [comment]
I have the same issue.  I need to use these two extensions.

**Comment by mpryvkin** [comment]
I'm working on update to add support for FixedColumns extension.

**Comment by s0By** [comment]
For my thing, I decided not to use the FixedColumn solution. There are problems with row selection when using it and it clutters the dom with extra tables. I'm sticking to a css solution and just position absolute the needed columns.

**Comment by charlesshenxc** [comment]
Hi mpryvkin,

Thanks for the update and your great work. My problem has been solved.

**Comment by s0By** [comment]
How to properly listen for the "change" when using checkboxes with FixedColumns?

Previously I used 
`$(table.table().container()).on('change', 'input[type="checkbox"]', function() {`
But this doesn't get the "select all" checkbox now.

**Comment by mpryvkin** [comment]
Please try the code below to handle "Select all" change event:

```
$(table.table().container()).on('change', 'thead th.dt-checkboxes-select-all input[type="checkbox"]', function() {
}
```

**Comment by s0By** [comment]
`$(table.table().container()).on('change', 'thead th.dt-checkboxes-select-all input[type="checkbox"]', function() {
}` 
Nope, this doesn't work. Only if used without fixedColumns. Also, it's not the best approach, since I need to look for every checkbox change, general idea is to recount selected inputs base on current selection.

**Comment by mpryvkin** [comment]
Strange, maybe I'm missing something, will test. 
In the meantime, can you attach handler to [select](https://datatables.net/reference/event/select) and [deselect](https://datatables.net/reference/event/deselect) events to do that, that could be more future proof? For example:
```
table.on('select deselect', function(e, api, type, indexes){
});
```

**Comment by s0By** [comment]
I'll play around, maybe I'll find something. 
Don't remember why, but Select extension didn't really suit my needs. 
I'm not allowed to select the whole row by clicking anywhere.

I used "selecting" from your solution, had to slightly tune it tho. In my solution, I'm able to select the row by clicking on the checkbox. 
In the `updateCheckbox` function in the bottom I have: 

```
if(nodes.length){
         dt.$(nodes).find('input[type="checkbox"]').prop('checked', isSelected);

         if(isSelected){
            $(dt.$(nodes).closest('tr')).addClass('selected');
         } else {
            $(dt.$(nodes).closest('tr')).removeClass('selected');
         }
      }
```
I created option `selectByCheckbox` as well, but couldn't figure out how to properly check for it without extra iterations, so the solution partially done at the moment.

**Comment by s0By** [comment]
Maybe something is wrong with my solution, but I think fixedColumns also doesn't get the deselect method as well, my external button doesn't work if I init fixedColumns.
```
$(selector).on('click', function(e){
       e.preventDefault();
       table.column(0).checkboxes.deselect();
});
```
