### ISSUE TITLE
Rows Selected not clear when api.ajax.reload()

### ISSUE THREAD

**Issue by SherwinVN** [gyrocode/jquery-datatables-checkboxes#130]
when i use api.column(1).checkboxes.selected() get row selected, 
but it not refresh select when api.ajax.reload()

1. checked row one => 1 checked
2. checked row two=> 2 checked
3. api.ajax.reload()
4. checked row one => 3 checked

plz help me?

**Comment by mpryvkin** [comment]
Unfortunately this is limitation of the plugin at the moment. 

As a workaround please deselect all checkboxes before reloading the table.

For example:
```
api.column(0).checkboxes.deselectAll();
api.ajax.reload();
```

**Comment by SherwinVN** [comment]
Thank you so much!

**Comment by SherwinVN** [comment]
OMG! 
api.column(...).checkboxes.deselectAll is not a function
=> Checkboxes 1.1.0
