### ISSUE TITLE
Checkbox value disappears when checkboxes are rendered

### ISSUE THREAD

**Issue by WillYouth** [gyrocode/jquery-datatables-checkboxes#136]
Before checkboxes are rendered:
![image](https://user-images.githubusercontent.com/22805266/146347942-d881a4fb-0d77-4bb3-a5c0-2b623b88b4ef.png)

After checkboxes are rendered:
![image](https://user-images.githubusercontent.com/22805266/146348116-c44a5dc3-b072-4ae0-9127-14c569925fe0.png)

My code:
```
table = $('#serviceItemList').DataTable({
    scrollY: 500,
    paging: false,
    dom: 'Bfrtip',
    info: false,
    columnDefs: [
        {
            targets: 0,
            checkboxes: true
        }
    ],
    select: true
});
```

**Comment by mpryvkin** [comment]
Plugin replaces content of the cell with own generated content `<input type="checkbox" class="dt-checkboxes">`.

You can use the following markup for your cells containing checkboxes `<td>XXX</td>` where XXX is unique value, for example `<td>309</td>`, etc. 

Then prepare input values for submission using the code shown on [this page](https://www.gyrocode.com/projects/jquery-datatables-checkboxes/). For example:
   
```
   // Handle form submission event
   $('#frm-example').on('submit', function(e){
      var form = this;

      var rows_selected = table.column(0).checkboxes.selected();

      // Iterate over all selected checkboxes
      $.each(rows_selected, function(index, rowId){
         // Create a hidden element
         $(form).append(
             $('<input>')
                .attr('type', 'hidden')
                .attr('name', 'items[]')
                .val(rowId)
         );
      });
   });
```

**Comment by WillYouth** [comment]
Thanks for the awesome answer! It solves my problem. But I also discovered another new issue regarding missing checkbox checked status. I will open another issue and close this. Please help with my issue. Thanks a lot!
