### ISSUE TITLE
Plugin breaks KeyTable plugin

### ISSUE THREAD

**Issue by Miro-Sandberg** [gyrocode/jquery-datatables-checkboxes#140]
This plugin has issues working together with datatables keyTable plugin.
If I load this before keyTable, datatables table.keys is undefined
If I load this after keyTable, table.keys works but table.column(0).checkboxes is undefined

**Comment by mpryvkin** [comment]
I could not recreate the problem, see [this example](https://jsfiddle.net/gyrocode/h5btwakm/).
