### ISSUE TITLE
"indeterminate" is not work

### ISSUE THREAD

**Issue by atkuo090** [gyrocode/jquery-datatables-checkboxes#141]
![image](https://user-images.githubusercontent.com/106139700/169964699-4b66a820-ee95-4f17-b435-af362a2e64b1.png)

Problem with Checkbox 1.2.12. DataTables 1.11.5:
When I just select one item ,it still appear select-all

**Comment by sadeghbarati** [comment]
@mpryvkin 

custom Bootstrap checkbox also not working 
```js
columnDefs: [{
         targets: 0,
         render: function (data, type, row, meta) {
            if (type === "display") {
               data =
                  '<div class="checkbox form-check"><input class="dt-checkboxes form-check-input" type="checkbox"><label></label></div>';
            }

            return data;
         },
         checkboxes: {
            selectRow: true,
            selectAllPages: false,
            selectAllRender: '<div class="checkbox form-check"><input class="dt-checkboxes form-check-input" type="checkbox"><label></label></div>',
         },
      },
      {
         data: null,
         defaultContent: "",
         className: "control",
         orderable: false,
         targets: 1,
      },
   ],
   responsive: {
      details: {
         type: "column",
         target: 1,
      },
   },
   select: {
      style: "multi",
      selector: "td:not(.control)",
   },
```

**Comment by sadeghbarati** [comment]
dataTables.checkboxes.js `v1.2.9` ✅ works in jsfiddle examples
```js
var isSelected;
var isIndeterminate;

// If none of the checkboxes are checked
if (countChecked === 0) {
   isSelected = false;
   isIndeterminate = false;

   // If all of the checkboxes are checked
} else if (countChecked === cellsData.length) {
   isSelected = true;
   isIndeterminate = false;

   // If some of the checkboxes are checked
} else {
   isSelected = true;
   isIndeterminate = true;
}
```
---

dataTables.checkboxes.js `v1.2.13` ❌ 
```js
var isSelected;
var isIndeterminate;

// If none of the checkboxes are checked
if (countChecked === 0) {
   isSelected = false;
   isIndeterminate = false;

   // If all of the checkboxes are checked
} else if ((countChecked + countDisabled) === cellsData.length) {
   isSelected = true;
   isIndeterminate = false;

   // If some of the checkboxes are checked
} else {
   isSelected = true;
   isIndeterminate = true;
}
```

**Comment by mpryvkin** [comment]
Sorry, I cannot replicate it.

I updated a few examples ([Basic Initialization](https://jsfiddle.net/gyrocode/tqda3ovk/), [Styling - Awesome Bootstrap Checkbox](https://jsfiddle.net/gyrocode/j5u40azu/)) to 1.2.13 and they all work correctly in Firefox, Chrome and MS Edge.

If you could share an example demonstrating the problem based on one of the examples above, that would help to locate the issue. Thanks!

**Comment by sadeghbarati** [comment]
@mpryvkin 

https://m9ig5x.sse.codesandbox.io/

**Comment by sadeghbarati** [comment]
> Sorry, I cannot replicate it.
> 
> I updated a few examples ([Basic Initialization](https://jsfiddle.net/gyrocode/tqda3ovk/), [Styling - Awesome Bootstrap Checkbox](https://jsfiddle.net/gyrocode/j5u40azu/)) to 1.2.13 and they all work correctly in Firefox, Chrome and MS Edge.
> 
> If you could share an example demonstrating the problem based on one of the examples above, that would help to locate the issue. Thanks!




[Basic Initialization](https://jsfiddle.net/gyrocode/tqda3ovk/) 
```js
'ajax': 'https://gyrocode.github.io/files/jquery-datatables/arrays_id.json',
//without columns
```

[Modified Basic Initialization](https://jsfiddle.net/w9h2xoke/)
```js
'ajax': 'https://gyrocode.github.io/files/jquery-datatables/objects.json',
```

**Comment by mpryvkin** [comment]
The problem was with using [objects](https://gyrocode.github.io/files/jquery-datatables/objects.json) as data and not using [columns.data](https://datatables.net/reference/option/columns.data) option to specify data to be used by column containing checkboxes.

The solution is to specify data using [columns.data](https://datatables.net/reference/option/columns.data) option, see [jsfiddle.net/1as42f6t/](https://jsfiddle.net/1as42f6t/).
