### ISSUE TITLE
Investigate 0,1,2,3 appear instead of checkbox

### ISSUE THREAD

**Issue by lenamtl** [gyrocode/jquery-datatables-checkboxes#142]
Hi,

I'm updating my application template and script with the latest Datatables, JQuery and Bootstrap.

Case 1:
The issue is that the **0** or other array number appear instead of the checkbox on all table that have the features.

Case 2: When I refresh the page I can clearly see the array  0, 1 , 2, 3 then it get replaced by the check box.

**Comment by mpryvkin** [comment]
Can you please provide jQuery, jQuery DataTables and Bootstrap version numbers? Thanks!

**Comment by lenamtl** [comment]
Hi, 

Here is my actual setup:

Bootstrap   5.0.2
jQuery        3.6.0
Datatables 1.12.1
jQuery DataTables Checkboxes 1.2.13

During my tests

**Case 1:**
The issue is that the 0 appear instead of the checkbox on all table that have the features.
// I have not reproduced it yet
// The number did not get refreshed by the checkboxe 
// This occurred on tables that have only 1 row (not sure if this is important)
// This is blocking because there is no checkboxe

**Case 2:** 
When I refresh the page I can clearly see the array number 0, 1 , 2, 3 then it get replaced by the checkboxe.
This is fast, but I can see it.
// I realized that it was present before the update, I never paid attention to this but now I see this :)
// This is probably normal as the checkboxe replace the number during the load
// This is not blocking I can live with this.

Extra notes:
I'm using responsive
So responsive is set to column 0 and checkboxe to column 1
I'm using stateSave but I'm not saving the checkboxe state.

I know that sometimes the order of the loading Datatables plugins script can cause issue with Datatables.
I will make more tests and let you know.
