### ISSUE TITLE
Support DataTables v2

### ISSUE THREAD

**Issue by sadeghbarati** [gyrocode/jquery-datatables-checkboxes#145]
@mpryvkin 

https://cdn.datatables.net/2.0.0

DataTables v2 deprecated/removed internal API so it should use public APIs but I don't know how and can't make a PR.
The Release Changelog is not clear

The error line after I update DataTables to v2
https://github.com/gyrocode/jquery-datatables-checkboxes/blob/master/js/dataTables.checkboxes.js#L150

**Comment by sadeghbarati** [comment]
@AllanJard sry for mentioning and thanks for v2

**Comment by mpryvkin** [comment]
Thank you for your report! I definitely used some undocumented methods to improve performance or add functionality (such as `DataTable.ext.internal._fnColumnOptions`) so will look into adding support for DataTables v2.0.

**Comment by pichutan** [comment]
Hey there, 
Any timeframe when a official version for datatables 2.0.3 will be available?

**Comment by mpryvkin** [comment]
@pichutan, planning to release preliminary version later this month inspired suggestions in patch #145 by @alexsilva.

**Comment by pichutan** [comment]
Hey @mpryvkin, I'm glad to hear this! Thank you!

**Comment by diesl** [comment]
@mpryvkin I just wanted to note that [DataTables 2.1 has been released](https://datatables.net/blog/2024/datatables-2.1) in the meantime. Maybe you can check for compatibility with the new version as well

**Comment by mpryvkin** [comment]
@diesl, thank you!

**Comment by mpryvkin** [comment]
Added a [new branch](https://github.com/gyrocode/jquery-datatables-checkboxes/tree/feature-datatables-v2-support) with jQuery DataTables v2 support inspired by PR #147 by @alexsilva. @alexsilva, @sadeghbarati, and @diesl, please test in your code and let me know if you see any issues. Thank you!

**Comment by pichutan** [comment]
Hey @mpryvkin ,

I tested it with DT 2.1.3 and BT5 and it seems to work. There is also no error in the log, but I just initialized it and did no further testing about functionalities.

**Comment by pichutan** [comment]
Hey there, I would like to ask again - maybe somebody else tested it? I would love to use a new released version 👍

**Comment by mpryvkin** [comment]
Released [1.3.0](https://github.com/gyrocode/jquery-datatables-checkboxes/releases/tag/1.3.0) adding support for jQuery DataTables v2. Will continue to test and improve if any issues would be detected.
