### ISSUE TITLE
Flexibility

### ISSUE THREAD

**Issue by s0By** [gyrocode/jquery-datatables-checkboxes#15]
It's not an issue question, more like a proposition for enhancement.

Quite for sometime it's been popular to change the visuals of the checkbox, but to achieve that you need to hide the actual input and tweak the label and the html looks something like this: 

```
<div class="checkbox">
      <input type="checkbox">
      <label></label>
</div>
```

Also, in my case, I didn't like the select extension for datatable and I didn't want your checkbox extension to show how many checkboxes is selected either, so I had to add my own "setting option" `showInfo: false`

And tweaked one of the functions to get this 
```
// Update the table information element with selected item summary
if(ctx.aoColumns[i].checkboxes.showInfo) {
      $table.on('draw.dt select.dt deselect.dt', function () {
            self.showInfoSelected();
      });
}
```

It's not hard to "tamper" with the code, but It gets annoying whenever the solution gets updated and since all the main stuff is built into one function (constructor) I don't really see a point to extend the "Checkbox" class to avoid tweaking the code, since it's going to be basically the copy of the whole solution with a couple of my own lines.

Maybe it would be possible to put 2 of my solutions into the code, so users could set the things up to their taste. It doesn't really affect the functionality of the solution. Defaults could correspond to the current functionality, something like: 

```
showInfo: true,
checkboxHtml: '<input type="checkbox">'
```

If needed, I can even make a Pull request 👍

**Comment by mpryvkin** [comment]
Thank you for detailed comment and suggestion. 

You can set `selectRow: false` option which will stop showing number of selected rows in the information area. 
Regarding the checkbox HTML template, it sounds good, but it may cause many complications with the internal code. I will think about whether it would be possible.

**Comment by s0By** [comment]
The reason for my showInfo solution is that I want to keep the whole row selection functionality, but I just want to disable the total number.
