### ISSUE TITLE
Call to DataTable.ext.internal._fnApplyColumnDefs overrides my render option

### ISSUE THREAD

**Issue by emiljohansson** [gyrocode/jquery-datatables-checkboxes#16]
Hi,

I was trying to figure out why my render option was not working. After some digging it looks like my options are passed to `_fnApplyColumnDefs` in the base library. After that, this library is calling the same function and overriding all my settings. https://github.com/gyrocode/jquery-datatables-checkboxes/blob/master/js/dataTables.checkboxes.js#L107

My options:
```js
columnDefs: [{
  targets: 0,
  checkboxes: {
    selectRow: true
  },
  render: function (data, type, full, meta) {
    if (type === 'display') {
      data = '<input type="checkbox" class="dt-checkboxes hello"> Test template'
    }
    return data
  }
}]
```

The `render` function works for me if I comment out your implementation of the render option. Do you see any issues with my settings? Otherwise is it possible in this library to first validate if the render function has been declared?

Thanks

**Comment by mpryvkin** [comment]
There might be no issues now with your code now but you would have to keep patching the code with every update. 

Instead as a temporary workaround I suggest using [`columns.createdCell`](https://datatables.net/reference/option/columns.createdCell) option and modify cell that way.

For example:

```javascript
      'columnDefs': [
         {
            'targets': 0,
            'checkboxes': {
               'selectRow': true
            },
            'createdCell': function (td, cellData, rowData, row, col) { 
                $(td).css('background-color', 'red');
                $(td).append('Click me'); 
            }            
         }
      ],
```

See [this example](https://jsfiddle.net/snqw56dw/390/) for code and demonstration.
