### ISSUE TITLE
你好，我是用了你的datatables-checkboxes插件，但是遇到了点问题，需要请教一下。

### ISSUE THREAD

**Issue by yipanbo** [gyrocode/jquery-datatables-checkboxes#2]
我使用的是datatables-checkboxes插件，datatables开启了server模式，targets渲染在column 0 那一列。现在的问题是，我想在最后一列渲染一些别的数据，总是会收到datatables的提示，
![image](https://cloud.githubusercontent.com/assets/8718011/16798964/1d12ba78-4921-11e6-92fe-23ce6775af7e.png)
我感觉使用了datatables-checkboxes插件之后，datatables的columns属性会有点问题，please help me，thank you！

**Comment by yipanbo** [comment]
我在datatables的columns属性中这样配置了一下，
"columns": [
			        { "data": "", "defaultContent": "" },
	                        { "data": "name" },
	                        { "data": "username" },
	                        { "data": "mobile" },
	                        { "data": "mail" },
	                        { "data": "note" },
	                        { "data": "" }
	                    ],
其中第一行添加了 "defaultContent": "" ，这样就没有提示了，感觉现在还可以接受。

**Comment by yipanbo** [comment]
不太好，翻页又遇到问题了，还是请大神帮忙解决一下吧，谢谢了

**Comment by mpryvkin** [comment]
Please use English to report issues with the plug-in. If this is not an issue with **jquery-datatables-checkboxes** extension, please post support requests and questions in the DataTables forums at https://datatables.net/forums or at StackOverflow at http://stackoverflow.com with tag `datatables`. Support requests posted here will be closed.
