### ISSUE TITLE
Number of rows selected in the footer shows 1 

### ISSUE THREAD

**Issue by charlenecoffman** [gyrocode/jquery-datatables-checkboxes#20]
The standard footer for the datatable is showing 1 row selected when a row is selected but the number does not increase when more are selected. Additionally, selecting the "selectall" checkbox at the top shows 1 row selected.

**Comment by mpryvkin** [comment]
Can you create an example on [jsFiddle.net](http://jsfiddle.net/) to demonstrate the problem? [Example on project page](http://www.gyrocode.com/projects/jquery-datatables-checkboxes/) shows correct number of selected rows in the info area.

**Comment by Stahet** [comment]
I have the same issue, I created an example on jsFiddle.net https://jsfiddle.net/fcfc8t4n/. The html example was taken from https://datatables.net/extensions/select/examples/initialisation/checkbox.html

**Comment by mpryvkin** [comment]
Thanks for the example. This occurs because column containing checkboxes has to have unique values. See [updated jsFiddle](https://jsfiddle.net/fcfc8t4n/3/).
