### ISSUE TITLE
Can read name form selected row?

### ISSUE THREAD

**Issue by PsKs** [gyrocode/jquery-datatables-checkboxes#24]
Hi sir.
Thank you for your plugin it is benefit for me.
But I like name and ID return when i click checkbox button.
I get ID but name of row is not return.
Please can you help me.

**Comment by mpryvkin** [comment]
Can you create an example based on [this jsFiddle](https://jsfiddle.net/gyrocode/snqw56dw/) to demonstrate the problem?

**Comment by PsKs** [comment]
This is example from [jsFiddle](https://jsfiddle.net/p331rgoj/).
My problem is when I click next pagination my name of array `rows_name_selected` is set to zero.
I want like `rows_selected` varaible. 

PS. Sorry for my poor english.

**Comment by mpryvkin** [comment]
There is a mistake in your code, see [updated example](https://jsfiddle.net/p331rgoj/1/)

**Comment by PsKs** [comment]
OwO, I mistake. Thank you very much.
