### ISSUE TITLE
Shift click checkboxes to select range of rows

### ISSUE THREAD

**Issue by andrewlube** [gyrocode/jquery-datatables-checkboxes#25]
Hi,

I'd like the ability the ability to select a range of rows by using the shift key on the checkbox.

The `Select` extension provided by DataTables allows for the option `multi+shift`. This allows you to select a range of rows by shift clicking.

Currently, shift-clicking on the checkbox itself does not highlight the range of rows. Shift clicking outside of the checkbox will however highlight the range

Any advice on a way I could achieve the desired result?

**Comment by mpryvkin** [comment]
You need to use `os` value for `select.style` option in order for <kbd>Shift</kbd> to work. 

However I see the problem in [this example](https://jsfiddle.net/47jzysg9/3/) where range of rows is not selected when checkbox is <kbd>Shift</kbd> clicked. It works fine when <kbd>Shift</kbd> clicking outside of the checkbox as you indicated.
