### ISSUE TITLE
All Rows Selected When Paging Through Server-side Data

### ISSUE THREAD

**Issue by OliverHrdz** [gyrocode/jquery-datatables-checkboxes#28]
I have a DataTable with server-side processing on.  The AJAX request returns an array of objects that I map in the DataTable with the "columns" option.  If I check one or more rows, and switch pages, all rows are selected on every subsequent page.  If no rows are checked, then no rows are checked on subsequent pages I switch through.

**Comment by mpryvkin** [comment]
Make sure the column that contains checkboxes has unique data for each row.  See [project page](http://www.gyrocode.com/projects/jquery-datatables-checkboxes/) and go to "Ajax" tab under the table, notice IDs - 1, 2, 3...  for the column that contains checkboxes.

From your description it sounds like your data is not unique or absent which causes plug-in to think that the row is checked when in fact it is not.

I'm closing this issue. If you think this is a bug in the plug-in and can create an example proving so, please submit your example and re-open the issue.

**Comment by OliverHrdz** [comment]
There is a unique key column in the returned data.  I'll try to get an example up to reproduce the issue.

**Comment by mpryvkin** [comment]
Use http://myjson.com/ and post a sample of your data and use [this jsFiddle](https://jsfiddle.net/gyrocode/snqw56dw/) as a starting point.

**Comment by OliverHrdz** [comment]
I'm having trouble reproducing the issue in jsFiddle as the table is not fully rendering the check boxes as expected.  Also, I don't think I would be able to fully reproduce a server-side DataTable as the draw property in the response is the same for each AJAX request as I'm returning static data from Myjson.  Please take a look at: https://jsfiddle.net/wn5637La/36/.  The only difference from your example is that I'm returning objects instead of a 2D array.  The unique column is the "equipmentId" property.  Thanks!

**Comment by OliverHrdz** [comment]
I've figured it out.  I didn't realize that this plugin requires the unique ID column to be the same column as the check box, which typically is the first column.  So I removed the `defaultContent:` property from the `columnDefs` option, and set the `columns.data` for the first column to the key "equipmentId" instead of `null`.  I have it working now in my application, and updated the jsFiddle page, but for some reason there it still isn't rendering the table right.  In any case, I'm good now, so hopefully this may help anyone else that may come across this issue.

**Comment by hycday** [comment]
@OliverHrdz : this is exactly the issue I am having, could you please develop more on the steps you did to fix it ?
I have a column with unique IDs (first column), and a column with the checkboxes (last column), I get it that I have this issue because I need unique IDs on the last column, but you seemed to have found a workaround, could you please describe the steps in a simple/noob way please ?

thanks !!
