### ISSUE TITLE
Checkbox select not working as expected

### ISSUE THREAD

**Issue by wimoMisterX** [gyrocode/jquery-datatables-checkboxes#3]
When you click on several checkboxes on a page and move on to other pages all the rows get selected in every page and the number of rows selected is always 1 when 1 or more checkboxes are selected. 

I have the following options used: deferRender: true, processing: true, serverSide: true

**Comment by mpryvkin** [comment]
Sounds strange. Unfortunately I cannot reproduce the problem with the options you have mentined `deferRender: true, processing: true, serverSide: true`. Can you please show all of your initialization options?

**Comment by wimoMisterX** [comment]
Here are my initialization options, I hope this issue is fixed as soon as possible!

```javascript
var myTable = $('#my_Table').DataTable({
    order: [
        [1, 'asc']
    ],
    ajax: {
        url: "xx",
    },
    columns: [{
        "defaultContent": "-",
        "checkboxes": {
            'selectRow': true
        }
    }, {
        "data": "id",
        "render": function(data, type, row, meta) {
            var link = "xx" + data;
            return '<a href=' + link + '>' + data + '</a>';
        }
    }, {
        "data": "name"
    }, {
        "data": "price",
        "width": "147px"
    }, {
        "data": "quantity",
        "width": "147px"
    }],
    deferRender: true,
    processing: true,
    serverSide: true,
});
```

**Comment by mpryvkin** [comment]
I have created [Server-side processing exampl](http://www.gyrocode.com/projects/jquery-datatables-checkboxes/examples/server-side-processing/) and temporarily added `deferRender: true` option but it seems to be working fine. Please make sure you're using the latest jQuery DataTables, Select extension and Checkboxes extension as mentioned on the [project page](https://www.gyrocode.com/projects/jquery-datatables-checkboxes/)

**Comment by wimoMisterX** [comment]
Thank you!
