### ISSUE TITLE
error default selected

### ISSUE THREAD

**Issue by yoyo837** [gyrocode/jquery-datatables-checkboxes#31]
First, I'm very sorry that my English is relatively poor;

When i selected one row, then call [table].ajax.reload() method, all new rows is selected by default.

How to solve this problem?

Thanks for your reply!

**Comment by mpryvkin** [comment]
See issue #28 and make sure the column that contains checkboxes has unique data for each row.

I'm closing this issue. If you think it is a bug and can create an example using [this jsFiddle](https://jsfiddle.net/gyrocode/snqw56dw/) as a starting point, please re-open it.
