### ISSUE TITLE
UI problem when unselecting row by using checkbox directly (and Select extension activated)

### ISSUE THREAD

**Issue by os1r1s110** [gyrocode/jquery-datatables-checkboxes#33]
Hi there, I fell on your blog post by searching how to implement checkboxes in a clear manner in datatables and it's really a good extension.

I also saw the notice about a workaround you have made not long ago and I would like to report unexpected behavior. 

When I select a row (no matter if I do it through the checkbox or by clicking anywhere on the line because of the Select selector), everything works fine, the row is selected and the checkbox status is updated correclty.

When I deselect the row though, it doesn't work if I do it through the checkbox directly. I narrowed down the problem source to this piece of code (~line 578):
` // If state of the checkbox needs to be updated

            if(hasData !== ctrl.checked){
               self.updateCheckbox('cell', [cellIdx], hasData);
               self.updateSelectAll(colIdx);
            }`

I tried commenting it out and then everything started working fine again. I still don't know why it causes this bug, but at least I have an idea of where it's coming from (well, I hope so ahah)

BTW: I know it works on your blog so I'm trying to find where the problem is on my side, I was just noticing you as you asked for it, because it may be a small incompatibility with another plugin/extension.

**Comment by mpryvkin** [comment]
Please retrieve the latest code (version 1.2.3 as of now) from the repository and try again. I had pushed commit today that broke some functionality and had to revert back.

**Comment by os1r1s110** [comment]
Still the same behavior on my side :( 

Sorry for this... But as I said, I'm still searching on my side too to find the root cause.

**Comment by os1r1s110** [comment]
Let it be! 
After clearing cache and recompiling again to make sure everything was fresh, it it working as expected 👍

**Comment by os1r1s110** [comment]
UPDATE: Oops, I was wrong, the problem still appears when more than one row is selected... :(

**Comment by mpryvkin** [comment]
Please post your DataTables initialization code. Creating an example demonstrating the problem would help too, you can start with [this example](https://jsfiddle.net/gyrocode/snqw56dw/).

**Comment by os1r1s110** [comment]
Here you go. 
[sample.zip](https://github.com/gyrocode/jquery-datatables-checkboxes/files/903909/sample.zip)

**Comment by mpryvkin** [comment]
The problem is that you don't specify data source for the checkbox column. It MUST have data source with unique values.

Instead of this:
```
      {
        "data": null
      }, // Checkboxes
```
you need to use this:
```
      {
        "data": "Id"
      }, // Checkboxes
```

**Comment by os1r1s110** [comment]
Yup, that seems to correct it on my side too. Thanks for your help! 

MY BAD! "Column containing checkboxes must have data which should be preferably unique. Using columns.data option set to null for the column containing checkboxes will result in unexpected behavior." Seems like I didn't read through the entire page.... It serves me right!

Thanks again and sorry for that, should have read through carefully :)

**Comment by mpryvkin** [comment]
Thanks for confirming! I added the statement yesterday to avoid confusion for other users.

**Comment by os1r1s110** [comment]
Ah, so I didn't miss it in my first reading.... whew (*^_^*) 

Thanks for closing, I forgot to.
