### ISSUE TITLE
Required version of DataTable

### ISSUE THREAD

**Issue by SilasOlatayo** [gyrocode/jquery-datatables-checkboxes#36]
I think it will be appropriate to state the required version of Datatable in your new version.
I just got "TypeError: Cannot read property 'selectCallback' of undefined" when I upgrade form v1.1.3

You can close this after reading.

**Comment by mpryvkin** [comment]
Thanks for reporting the issue, added "Available Since: Version 1.2" notice in the [Options](https://www.gyrocode.com/projects/jquery-datatables-checkboxes/reference/options/) section.
