### ISSUE TITLE
selected rows count is wrong

### ISSUE THREAD

**Issue by starcraft0429** [gyrocode/jquery-datatables-checkboxes#37]
Select rows by tapping on rows.
and click "-" sign (selectAll/unselectAll).
then, selected row count is not working in bottom bar

**Comment by mpryvkin** [comment]
I believe this has been already fixed, see #34 for more details. Can you upgrade to the most recent version and see if the issue still persists.

**Comment by starcraft0429** [comment]
I just download min.js
btw, now it is now working 
cant select row

**Comment by starcraft0429** [comment]
[dataTables.checkboxes.min.js.zip](https://github.com/gyrocode/jquery-datatables-checkboxes/files/976124/dataTables.checkboxes.min.js.zip)
I am using this.(this has count error)

btw, If I use new in this repository, row selecting never work.

thanks in advance

**Comment by tomtopweb** [comment]
Selecting row disappeared from the current version to me as well or do I need to add new call for that function?

**Comment by mpryvkin** [comment]
What do you mean by "selecting row disappeared from the current version"? Plug-in requires column containing checkboxes to have unique data.

Can you please replicate the issue using [this example](https://jsfiddle.net/gyrocode/snqw56dw/) as a start?

**Comment by tomtopweb** [comment]
Sorry, I just repudiated with the example and it works well! Thanks!
