### ISSUE TITLE
Select all selects disabled checkboxes

### ISSUE THREAD

**Issue by Emarcus25** [gyrocode/jquery-datatables-checkboxes#38]
When I click the select all checkbox in a table header, it selects all checkboxes, even when they are disabled or read only. 

Version:  1.1.0-alpha.1

**Comment by mpryvkin** [comment]
Plug-in currently doesn't support disabled or read-only checkboxes. Also I would recommend to upgrade to the most recent version.

**Comment by mpryvkin** [comment]
I'm currently working to add support for disabled checkboxes, please stay tuned.
