### ISSUE TITLE
how can i initialize the selected state from database

### ISSUE THREAD

**Issue by nguyenhaiphan** [gyrocode/jquery-datatables-checkboxes#40]
Firstly, I'd like to thank you very much for your effort.

Secondly, my question is how can I implement the state to table.column(colId).checkboxes.select(), so that I can initialize the selected rows from my saved data into the DataTables?

**Comment by nguyenhaiphan** [comment]
I figured it out. I implement the createdCell callback from columnsDef, for example:
Note: 
- the initialList is an array such as [1,5,22,..]
- myDataTable holds the datatable object after dataTable intialization step.
```
        columns: [
            {
                targets: 0,
                data: 'id',
                className: 'dt-head-center dt-body-center',
                checkboxes:  {
                    selectRow: true,
                    selectCallback: function(nodes, selected){
                        $('input[type="checkbox"]', nodes).iCheck('update');
                    },
                    selectAllCallback: function(nodes, selected, indeterminate){
                        $('input[type="checkbox"]', nodes).iCheck('update');
                    }
                },
                createdCell: function (cell,cellData,rowData,rowIndex, colIndex ){
                    if ((initialList.indexOf(rowData['id'])!==-1)){
                        myDataTable.cell(rowIndex, colIndex).checkboxes.select(true);
                    }
                },
...
```

**Comment by mpryvkin** [comment]
Yes, using `createdCell` is the best way to do it. This has been demonstrated in [this example](https://www.gyrocode.com/projects/jquery-datatables-checkboxes/examples/api/disable-checkboxes/). I will add similar example demonstrating how to select checkboxes during initialization.
