### ISSUE TITLE
[propose] Event trigger after selection set has been changed state

### ISSUE THREAD

**Issue by nguyenhaiphan** [gyrocode/jquery-datatables-checkboxes#41]
Thank for your great plugin.

Do you have any intention to support event after the selection set has been changed state?

**Comment by mpryvkin** [comment]
This has already been implemented, see [columns.checkboxes.selectCallback](https://www.gyrocode.com/projects/jquery-datatables-checkboxes/reference/options/#columns.checkboxes.selectCallback) for handling event when state of the checkbox changes and [columns.checkboxes.selectAllCallback](https://www.gyrocode.com/projects/jquery-datatables-checkboxes/reference/options/#columns.checkboxes.selectAllCallback) for handling event when state of the "select all" control changes.

**Comment by nguyenhaiphan** [comment]
Thank you very much

**Comment by legreco** [comment]
@mpryvkin can you give me a example code on this ?

**Comment by mpryvkin** [comment]
See [this example](https://www.gyrocode.com/projects/jquery-datatables-checkboxes/examples/styling/icheck/) demonstrating use of [columns.checkboxes.selectCallback](https://www.gyrocode.com/projects/jquery-datatables-checkboxes/reference/options/#columns.checkboxes.selectCallback) and [columns.checkboxes.selectAllCallback](https://www.gyrocode.com/projects/jquery-datatables-checkboxes/reference/options/#columns.checkboxes.selectAllCallback).

**Comment by legreco** [comment]
Yes, I just see them, but i have another problem2,
1. when the page first load the selectAllCallback is called
2. I i click on a row checkbox the selectAllCallback is also called

My code:
`   columnDefs: [
                {
                    'targets': 0,
                    'checkboxes': {
                        'selectRow': true,
                        'selectAllCallback': function(nodes, selected, indeterminate){
                          alert('function is called');
                        }
                    },

                }

            ],
            'select': {
                'style': 'multi'
            },`

**Comment by legreco** [comment]
Here is an example
[https://jsfiddle.net/legreco/6wegnxLz/]() of this behavior
