### ISSUE TITLE
Select All not working in IE/Safari

### ISSUE THREAD

**Issue by thepgchris** [gyrocode/jquery-datatables-checkboxes#43]
When using the select all check box in th,  check boxes are not selected/deselected. 

Tested in iOS safari and IE 11
Edit: using version 1.2.9 of plugin

**Comment by mpryvkin** [comment]
I can't replicate the issue with IE 11, [this example](https://www.gyrocode.com/projects/jquery-datatables-checkboxes/) works for me correctly. 

Can you please replicate the issue using [this example](https://jsfiddle.net/gyrocode/snqw56dw/) as a basis? Thanks!

**Comment by thepgchris** [comment]
Thanks for the quick response, I resolved the issue. I was calling the draw function on change of select all. This worked on firefox and chrome but was causing the IE and safari issue.
