### ISSUE TITLE
Ajax request return 500 (Internal Server Error)

### ISSUE THREAD

**Issue by zetionz** [gyrocode/jquery-datatables-checkboxes#45]
Hi there, I have a problem with the codes for deleting multiple records using ajax request, here's the code:
Note: I use Laravel.
If I use this lines of code:
`{ targets: 0,
"checkboxes": {
"selectRow": true,
"selectCallback": function(nodes, selected){
$('input[type="checkbox"]', nodes).iCheck('update');
},
"selectAllCallback": function(nodes, selected, indeterminate){
$('input[type=checkbox]', nodes).iCheck('update');
}
} 
}`
I get error 500, however if I remove the code, I can delete the records without any errors.
For the controller:
`public function removeSelected(Request $request)
    {
        foreach($request['id'] as $id){
            $user = User::findOrFail($id);
            $user->delete();
        }
    }`
and for delete button, I use button with onClick="deleteAll()", here's the code:
`function deleteAll(){
	if($('input:checked').length < 1){
		swal({
			title: 'Notice',
			text: 'Please select user(s) to remove',
			type: 'warning',
			html: true,
			confirmButtonColor: "#DD4B39",
			confirmButtonText: "Confirm",
		});
	}else if
	(
		swal({
			title: 'Warning',
			text: 'Are you sure to remove the selected user(s)?',
			type: 'warning',
			html: true,
			confirmButtonColor: "#DD4B39",
			confirmButtonText: "Yes",
			showCancelButton: true,
		},
		function(isConfirm) {
			if (isConfirm) {
				$.ajax({
					url : "{{ route('users.remove') }}",
					type : "POST",
					data : $('#form-users').serialize(),
					success : function(data){
						swal({
							title: 'Removed',
							text: 'All selected user(s) have been removed.',
							type: 'success',
							html: true,
							confirmButtonColor: "#DD4B39",
							confirmButtonText: "Confirm"
						}),
						Pace.restart(),
						$('table.display#tb_users').DataTable().ajax.reload();
					},
					error : function(){
						swal({
							title: 'Error',
							text: 'Something went wrong.<br/>Can\t remove selected user(s).',
							type: 'error',
							html: true,
							confirmButtonColor: "#DD4B39",
							confirmButtonText: "Confirm",
						});
					}
				})
			}
		})
	);
}
`
Thank you for your time

**Comment by mpryvkin** [comment]
Error 500 means server-side error so you need to inspect your logs. 

There are a few issues with your code.  `$('input:checked')` and `$('#form-users').serialize()` will only return elements for current page only . See [Submit all pages form data via Ajax request](https://www.gyrocode.com/articles/jquery-datatables-how-to-submit-all-pages-form-data/#solution-ajax) for more details on how to submit data from all pages.

**Comment by zetionz** [comment]
Hi there, thx for the hint, it worked now.
