### ISSUE TITLE
Plugin overrides jQuery after loading

### ISSUE THREAD

**Issue by band94** [gyrocode/jquery-datatables-checkboxes#46]
After loading the checkboxes script, I simply want to make an AJAX call with jQuery, for example:
```
$.ajax({
  'type': 'POST',
  'dataType': 'text',
  'url': 'my_specific_url',
  'data':  {... my data ... }
});
```
but it's go wrong. Every time when i try, the call try to run the DataTables ajax loading instead of running the generic AJAX call, what i want.
It seems to me, the plugin override the default jQuery plugin with it's $ attr.

Here is my loading order:
```
window.$ = window.jQuery = require('jquery');
require('bootstrap-sass');

require( 'datatables.net' );
require( 'datatables.net-bs' );
require( 'datatables.net-colreorder' );
require( 'datatables.net-fixedcolumns' );
require( 'datatables.net-fixedheader' );
require( 'datatables.net-responsive-bs' );
require( 'datatables.net-rowgroup' );
require( 'datatables.net-rowreorder' );
require( 'datatables.net-scroller' );
require( 'datatables.net-select' );

require('./datatables-checkboxes');
```

The DataTables table init and the jquery event handling comes after this.
Any idea what caused the trouble in my case?

**Comment by mpryvkin** [comment]
Plug-in should not override `$` function. Can you please remove `require('./datatables-checkboxes');` and see if the problem persist?

**Comment by band94** [comment]
I have already tried to remove the plugin, and after that everything worked fine for me. That was the main reason I opened the issue.

**Comment by mpryvkin** [comment]
Can you please create a sample project reproducing the problem?

**Comment by mpryvkin** [comment]
See [NPM instructions](https://datatables.net/download/npm), there are two optional arguments that you can provide when using `require`.
