### ISSUE TITLE
selectAllCallback strange behavior

### ISSUE THREAD

**Issue by legreco** [gyrocode/jquery-datatables-checkboxes#49]
It seems that selectAllCallback event doesnt operate as expected. According to docs this function get called if the select all checkboxe state is changed. But in this jsfiddle https://jsfiddle.net/legreco/6wegnxLz/
you can see the event is fired whatever checkboxes state is changed (it is called on page load too).
This is a very strange behavior.
I hope i am wrong somewhere in the code :)

**Comment by mpryvkin** [comment]
Good catch. I have been calling function defined by `selectAllCallback` option during redraws rather than state changes, which worked fine before. 

However I see your point, there is no need to call the function if the state hasn't been changed.
