### ISSUE TITLE
Server-side processing double ajax request on init.

### ISSUE THREAD

**Issue by s0By** [gyrocode/jquery-datatables-checkboxes#5]
I don't know if this is issue or not. 
In regular usage datatable does 1 ajax request using serverSide: true for Draw: 1.
When I connect your solution it does one extra ajax request with Draw: 2 

Is it a bug? If not why do we have 2 requests. In normal ajax usage you use only 1 request.

**Comment by mpryvkin** [comment]
Thanks for reporting, it could be a bug. I see it now in my [server-side example](http://www.gyrocode.com/projects/jquery-datatables-checkboxes/examples/server-side-processing/) too.
