### ISSUE TITLE
New functions like enableAll(), disableAll() and reset() 

### ISSUE THREAD

**Issue by nikitul** [gyrocode/jquery-datatables-checkboxes#51]
There is a server side scenario when the user make a select in DataTables, and after that, sends some data (multiple submits) to the server and return success or failure from those submits.

In this case it is needed to show to the user those errors, and that's why it is not possible to use draw() the table (can only to invalidate them).

For those rows where we have a submit with failure, must provide another possibility of submit action.

For those rows where we have a submit  with success , must block a new submit action, because it was a success.

Until now everything is doable, with deselect and disable functions. 

The thing is that when the user try to reload the data (some filter functions), your plugin remembers the old settings. that's why a reset() or enableAll() function is needed.

Thank you again.

**Comment by Fonata** [comment]
If by "remember the old settings" you mean that the checked state is loaded from local storage, please have a look at #58. If it solves your problem, let us know here.

**Comment by nikitul** [comment]
Sorry for the late response.
I think is ok now with stateSave.
