### ISSUE TITLE
Have checkboxes selected on render

### ISSUE THREAD

**Issue by kleinjm** [gyrocode/jquery-datatables-checkboxes#53]
$recipeTable.DataTable({
        data: recipes,
        columns: [
          { title: 'Name', data: 'name' },
          { title: 'Categories', data: 'categoryNames' },
          { title: 'Times Cooked', data: 'times_cooked' },
          {
            title: 'This Week',
            data: 'this_week',
            checkboxes: {
              selectRow: true,
            },
          },
        ],
        select: {
          style: 'multi',
        },
        iDisplayLength: 100,
      });

It seems that I cannot get this to work with `data` specified. The incoming data value is a boolean. How could this be achieved?

**Comment by mpryvkin** [comment]
Column containing checkboxes should have unique values as data, otherwise plug-in will behave incorrectly, please see [Known Limitations](https://www.gyrocode.com/projects/jquery-datatables-checkboxes/).

**Comment by kleinjm** [comment]
Thanks for the fast response. So you can't prepopulate the data with booleans? Seems like that would be a pretty common use case

**Comment by mpryvkin** [comment]
For each column containing checkboxes you need to use [`columns.data`](https://datatables.net/reference/option/columns.data) option pointing to property uniquely identifying the row, for example record ID. 

You can use another boolean field if you want to select checkboxes on page load, see [Select checkboxes on page load](https://www.gyrocode.com/projects/jquery-datatables-checkboxes/examples/api/select-checkboxes/) example.
