### ISSUE TITLE
Not add select class on row

### ISSUE THREAD

**Issue by ThibaultMartinPenbase** [gyrocode/jquery-datatables-checkboxes#55]
Hello,
http://www.monde-rp.fr/test.html
Why my row isn't selected whith "row-selected" class in my exemple when I check row ?

Thank's

**Comment by mpryvkin** [comment]
You forgot to include Select extension. 

Please avoid posting questions here and use [this discussion](https://www.gyrocode.com/articles/jquery-datatables-row-selection-using-checkboxes-and-select-extension/#respond) instead.

**Comment by ThibaultMartinPenbase** [comment]
How intall select extension ?

**Comment by mpryvkin** [comment]
Use [Download Builder](https://datatables.net/download/index) and include Select extension in addition to all themes and extensions needed.
