### ISSUE TITLE
Can't call cell().checkboxes.select(state) method after datatables load data from new url.

### ISSUE THREAD

**Issue by andymiaomiao** [gyrocode/jquery-datatables-checkboxes#56]
Sir , I want to use above method to check the checkbox of the selected row on row select event。the code is below:

```
vacationFormTable_table.on( 'select', function ( e, dt, type, indexes ) {
	if(type == 'row')
	{
		for(var i=0;i<indexes.length;i++)
		{
			vacationFormTable_table.cell(indexes[i],0).checkboxes.select(true);
		}
	}    		
});
```

every this if fine when the data loaded at first, but when i load data after from new url by click the button, like:  

```
$('#vacationFormTable').DataTable({
            destroy:true,
            ajax{url}
});
```
the above method report error like after select a row:

```
dataTables.checkboxes.js:433 Uncaught TypeError: Cannot set property '690' of undefined
    at u.<anonymous> (dataTables.checkboxes.js:433)
    at u.each (jquery.dataTables.min.js:98)
    at Checkboxes.updateData (dataTables.checkboxes.js:430)
    at u.<anonymous> (dataTables.checkboxes.js:978)
    at u.iterator (jquery.dataTables.min.js:100)
    at u.<anonymous> (dataTables.checkboxes.js:971)
    at u.<anonymous> (jquery.dataTables.min.js:104)
    at Object.select (jquery.dataTables.min.js:102)
    at HTMLTableElement.<anonymous> (index:1527)
    at HTMLTableElement.dispatch (jquery-2.2.3.min.js:3)
```

**Comment by Fonata** [comment]
@andymiaomiao Please surround your code with double backticks \`\` on a separate line before and after the code. You can use GitHub's Preview tab to see what it looks like. I kindly ask you to go ahead edit your issue text now.

Instead of destroying the datatable, what about just hiding it with CSS?

**Comment by mpryvkin** [comment]
Please re-test with the latest code and let me know if it fixes the issue. Thanks!

**Comment by andymiaomiao** [comment]
Thank you! I've changed code to "$('#vacationFormTable').DataTable().cell(indexes[i],0).checkboxes.select(true)";that works fine.
