### ISSUE TITLE
Code checking: ESLint compatibility

### ISSUE THREAD

**Issue by Fonata** [gyrocode/jquery-datatables-checkboxes#59]
The JavaScript here could become easier to maintain by following some of the suggestions of the ESLint tool. 

The rules not relevant to this project can be disabled in a `.eslintrc.json` file.

I especially worry about the shadowing of the undefined keyword.

**Comment by Fonata** [comment]
I have added the following monster to the beginning of this project's JavaScript file to see the IMHO critical rules' warnings first:

````javascript
/* eslint-disable spaced-comment,strict,space-in-parens,space-before-function-paren,space-unary-ops,no-undef,valid-jsdoc,lines-around-comment,brace-style,keyword-spacing,space-before-blocks,keyword-spacing,indent,quote-props,no-multi-spaces,space-infix-ops,object-curly-spacing,no-unused-vars */
````

**Comment by susgo** [comment]
I can have a look at this when implementing #35 (if this is still needed)
