### ISSUE TITLE
Selection on checkbox does not trigger datatable on select event

### ISSUE THREAD

**Issue by h2akim** [gyrocode/jquery-datatables-checkboxes#6]
Not sure this is only happen to me or a bug.

A datatables select event listener is not listen to the select event (although row is marked as selected) when I click on the checkbox .

Select event listener is working as expected if click on the row.

Thanks.

**Comment by mpryvkin** [comment]
I just tested the code and I get `select` event even when checkbox is clicked. See [this example](https://jsfiddle.net/snqw56dw/139/).

**Comment by h2akim** [comment]
Thanks @mpryvkin . Now work like a charm!
