### ISSUE TITLE
Prevent loading for some datatables if several on 1 page

### ISSUE THREAD

**Issue by Fonata** [gyrocode/jquery-datatables-checkboxes#61]
I have several Datatables on a single web page. I need checkboxes in one of them, but once I load this fantastic library, there are checkboxes in all my Datatables. 

What is the recommended way to load checkboxes only for one? I couldn't find any property or setting.

**Comment by mpryvkin** [comment]
Use element IDs to initialize individual tables separately.

For example:

```
var table1 = $('#example1').DataTable({
   // ... skipped ...
});

var table2 = $('#example2').DataTable({
   // ... skipped ...
});
```

See [this example](https://jsfiddle.net/uym5drwh/6/) for demonstration.
