### ISSUE TITLE
State saving only works on the first reload

### ISSUE THREAD

**Issue by DataTables** [gyrocode/jquery-datatables-checkboxes#64]
Just reported from a DataTables user: If you have state saving enabled and check a checkbox it will be correctly shown as selected if you reload. If you then reload the page again though, it is not selected.

It appears that the issue is that although the state is loaded it isn't then re-saved with the reselected checkbox information, so it can't be restored on the third page load.

**Comment by mpryvkin** [comment]
Yes, I can confirm. 
I have [State saving example](https://www.gyrocode.com/projects/jquery-datatables-checkboxes/examples/basic/state-saving/) where it doesn't work on third page load, but only if user doesn't interact with the table. If page is changed or table is sorted, the state is resaved.

Do you recommend to resave the state every time on page load?

**Comment by DataTables** [comment]
In this case yes - since you are augmenting the state object, once you are ready to augment it, you would need to call `state.save()`.
