### ISSUE TITLE
Wrong icon for select all checkbox with jquery-datatables-checkboxes 1.2.10

### ISSUE THREAD

**Issue by flowerpower** [gyrocode/jquery-datatables-checkboxes#66]
I'm using the solution in your latest example [here](https://github.com/gyrocode/jquery-datatables-checkboxes/issues/9#issuecomment-269342828) but with the last "jquery-datatables-checkboxes
" version 1.2.10 I have a little problem: for example I have a table with 2 rows, 1 row has a disabled checkbox like in your example, if I click the "select all checkbox" all works fine (selected only the row with checkbox enabled) but the "select all checkbox" icon is wrong! The result is an icon like I have not selected all rows. Can you help me?
![immagine](https://user-images.githubusercontent.com/2356911/40132972-941ed4a6-593e-11e8-94be-f2d504aec60a.png)

**Comment by mpryvkin** [comment]
Proper way to disable checkbox with `cell().checkboxes.enable()` and `cell().checkboxes.disable()` is shown in [this example](https://www.gyrocode.com/projects/jquery-datatables-checkboxes/examples/api/disable-checkboxes/). In that example, correct "select all" icon is shown even when some checkboxes are disabled.

The example you've mentioned was a workaround for an older version of the plugin.

If you want to hide a checkbox, here is [updated example](https://jsfiddle.net/adkx2kzp/37/) where icon is shown correctly. You need the latest DataTables code for the example to work correctly.

**Comment by Polkadot-js-ingratiating** [comment]
> Proper way to disable checkbox with `cell().checkboxes.enable()` and `cell().checkboxes.disable()` is shown in [this example](https://www.gyrocode.com/projects/jquery-datatables-checkboxes/examples/api/disable-checkboxes/). In that example, correct "select all" icon is shown even when some checkboxes are disabled.
> 
> The example you've mentioned was a workaround for an older version of the plugin.
> 
> If you want to hide a checkbox, here is [updated example](https://jsfiddle.net/adkx2kzp/37/) where icon is shown correctly. You need the latest DataTables code for the example to work correctly.





https://jqcode.space/questions/tips-for-concealing-table-rows-that-are-selected-with-checkboxes
