### ISSUE TITLE
Uncorrect displayed columns (shift) in example from documentation

### ISSUE THREAD

**Issue by PBrockmann** [gyrocode/jquery-datatables-checkboxes#67]
In the following example https://www.gyrocode.com/projects/jquery-datatables-checkboxes/examples/styling/awesome-bootstrap-checkbox/
I cannot see the name column. Names are present under the column 'Position'. The 'Salary' column is missing.

Another problem is multi option that is not clearly set in my understanding (compare this example to the default one)
Is it  
`
select: {
    style: 'multi'
  }
`
or 
`
select: 'multi'
`
?

Thanks for this very cool lib.

**Comment by mpryvkin** [comment]
Thanks for reporting the issue with the example, it has been corrected.

Both `select: { style: 'multi' }` and `select: 'multi'` are valid option, see [`select`](https://datatables.net/reference/option/select) option for more information.

**Comment by PBrockmann** [comment]
May I ask you to tell me why I cannot have the intermediate state (not none, not all) ?

Tested from https://jsfiddle.net/PBrockmann/zh8006zr/

**Comment by mpryvkin** [comment]
That's because first column has no data. It should have unique data, for example record IDs, etc.

**Comment by PBrockmann** [comment]
Ok thank you very much

**Comment by PBrockmann** [comment]
Indeed this column is there to host the checkbox.
So how to get an intermediate state then ?

Have you noticed that the number of rows does not change ? Always '1 row selected'

**Comment by mpryvkin** [comment]
Again, That's because first column has no data. See [updated example](https://jsfiddle.net/zh8006zr/8/) where first column has unique data - `1`, `2`, `3`, etc.

**Comment by PBrockmann** [comment]
OK I have duplicated an id column and indeed the intermediate state appears now. Sorry about my difficulty to understand this point.
