### ISSUE TITLE
Server Side Processing support broken in v1.2.10

### ISSUE THREAD

**Issue by dleffler** [gyrocode/jquery-datatables-checkboxes#68]
When using checkboxes v1.2.10 with server side processing, the xxx.selected() api call ONLY returns the checkboxes selected on the current page. I had to revert to v1.2.9 to get the entire list from all pages.

Also Is there a method to programatically load all the pages to populate the table?

**Comment by mpryvkin** [comment]
Thanks for reporting the issue!
