### ISSUE TITLE
Checkbox selection

### ISSUE THREAD

**Issue by s0By** [gyrocode/jquery-datatables-checkboxes#7]
Checkbox: selectRow': true would do the trick (maybe partly), because it fetches the row selection event even when I click on select all, but I'm not allowed to select the whole row. 

In my solution I'm able to select only the checkbox, when I click on other part of the row I get redirected. 

So the question is, could we have somekind of additional events to get something similar to checkboxes.selected. 

Checkboxes.selected doesn't work for me because if I put this for click event it gets a 1 selection less since it triggers before checkboxes is actually being activated. 

I'd like to have an event which would fetch the list at the moment I click on the checkbox.

**Comment by s0By** [comment]
Okey, I need to rephrase this, totally mislead you.

Checkboxes.selected() does the job, sort of. 

I used this function from your example ("submit" button)

```
var rows_selected = productsTable.column(0).checkboxes.selected();

        var form = $("#productListForm");
        var total_selected = 0;
        $.each(rows_selected, function(index, rowId){
            total_selected++;
            console.log(rowId);

            var exploded_product_id = rowId.split("_");

            // append only when clicked to submit something
            /*form.append(
             $('<input>')
             .attr('type', 'hidden')
             .attr('name', 'selected_products[]')
             .val(exploded_product_id[1])
             );*/
        });
        $(".total-selected-products").html("").html(total_selected);
```
It counts properly at the moment you click on the checkbox, it works in firefox and chrome, but it doesn't work in safari (was working on it, so didn't figure it out at first).

**Comment by s0By** [comment]
Updated a [fiddle](https://jsfiddle.net/snqw56dw/142/) from closed issue, so you'd understand what I'm talking about

**Comment by mpryvkin** [comment]
Thanks for interesting and well explained question. I see your point but can only suggest a workaround at this time. Use `setTimeout` with small delay in your `change` event handler to get correct number of selected rows.

See [updated example](https://jsfiddle.net/d5Ld0x7n/) for code and demonstration.
