### ISSUE TITLE
when  datatables editor update success,selected is gone...

### ISSUE THREAD

**Issue by treefung** [gyrocode/jquery-datatables-checkboxes#70]
https://editor.datatables.net/

when datatables editor update success, jquery-datatables-checkboxes selected is gone...

but datatables status is selected ?

**Comment by treefung** [comment]
i think about Css pseudo-element

**Comment by mpryvkin** [comment]
Please test with the most recent version of the plug-in. I have recently corrected issue #64 with state saving, maybe that is what was happening. 

If problem still persists, please show an example demonstrating the problem and re-open the issue.
