### ISSUE TITLE
Add custom class to checkboxes

### ISSUE THREAD

**Issue by smezae** [gyrocode/jquery-datatables-checkboxes#71]
There is some way to add custom classes to the rendered checkboxes? I only see the option for the selectAll, but i need to add some explicit class to the checkboxes in the rows

**Comment by mpryvkin** [comment]
See [Awesome Bootstrap Checkbox example](https://www.gyrocode.com/projects/jquery-datatables-checkboxes/examples/styling/awesome-bootstrap-checkbox/) for demonstration on how to use custom HTML markup.
