### ISSUE TITLE
Server Side checkboxes.selected only returning current page's selection

### ISSUE THREAD

**Issue by bikram-bikram** [gyrocode/jquery-datatables-checkboxes#74]
I recently converted my datatable from client side to server side. And the row selection used to work fine on the client side. it works great on server side also, but when i try to get the list of selected rows from multiple pages, I only get the current page's selection.

The count at the bottom of the table is correct and it includes the selection from all pages, Also, when I  go to a previous page, the selection is still there.

Only when I click my button and try to get the following:
table.column(0).checkboxes.selected()
I get the rows selected on the current page only. Is there a way to get it from all pages?

**Comment by mpryvkin** [comment]
Try downloading the most recent version of the code, that issue has been recently reported (#68) and corrected (https://github.com/gyrocode/jquery-datatables-checkboxes/commit/cb877bd20a543a063d0b0708afc03cf8a1bc4381).
