### ISSUE TITLE
Library doesn't load on Firefox > 6.0.1 

### ISSUE THREAD

**Issue by BDFINSEE** [gyrocode/jquery-datatables-checkboxes#75]
Javascript console error message : 

fail to load script from source //gyrocode.github.io/jquery-datatables-checkboxes/1.2.10/js/dataTables.checkboxes.min.js

Thanks a lot

**Comment by mpryvkin** [comment]
Can't confirm it, it works for me.

**Comment by mpryvkin** [comment]
If you are using older browser version that doesn't support double forward slash syntax, try using `https://gyrocode.github.io/jquery-datatables-checkboxes/1.2.10/js/dataTables.checkboxes.min.js` instead.
