### ISSUE TITLE
Datatable Return Empty

### ISSUE THREAD

**Issue by mulyawansentosa** [gyrocode/jquery-datatables-checkboxes#76]
Hello,
I need help to use this plugin. I have followed instruction on your website. But array return empty.
I open this issue on stakeoverflow:
https://stackoverflow.com/questions/51230289/datatable-checkbox-return-empty
Please help?

**Comment by mpryvkin** [comment]
In your context you need to use `column(0).checkboxes.selected()` instead of `columns(0).checkboxes.selected()`. Return value of API method `columns()` differs from `column()`.
