### ISSUE TITLE
Datatable show column value not checkbox

### ISSUE THREAD

**Issue by GitHubMouhssine** [gyrocode/jquery-datatables-checkboxes#77]
Hello,
I need help to use this plugin. I have followed instruction on your website to use server side. But return it column value not a checkbox. 
![bug](https://user-images.githubusercontent.com/14931015/44755612-d4a8c900-ab1e-11e8-8097-6641a224dd06.png)

**Comment by GitHubMouhssine** [comment]
I use cakephp3-datatable plugin
server JSON response : 
{
    "recordsTotal": 3,
    "recordsFiltered": 3,
    "draw": 1,
    "data": [
        {
            "id": 33,
            "numero": 3,
            "quantite": 9999.23,
        },
        {
            "id": 34,
            "numero": 2,
            "quantite": 20,
        },
        {
            "id": 36,
            "numero": 5,
            "quantite": 96521,
      },
    ]
}
DataTables initialization : 
$columns = [
            [
                'field' => 'Contrats.id',
                'data' => 'id',
                'visible' => true,
                'orderable' => false,
                'searchable' => false,
                'orderable' => true,
            ],
            [
				'field' => 'Contrats.numero',
				'data' => 'numero',
                'searchable' => true,
            ],
            [
				'field' => 'Contrats.quantite',
				'data' => 'quantite',
                'searchable' => true,
            ]];
$options = [
                                'serverSide' => true,
                                'processing' => true,
                                'ajax' => [
                                    'url' => $this->Url->build() // current controller, action, params
                                ],
                                'data' => $data,
                                //'deferLoading' => $data->count(), 
                                'columns' => $columns,
                                'columnDefs' => [
                                     [
                                        'targets' => 0,
                                        'checkboxes' => [
                                                'selectRow' => true,
                                        ],
                                     ]
                                ],
                                'select' => [
                                    'style' => 'multi',
                                ],
                            ];
                            echo $this->DataTables->table('dt-table', $options, ['class' => 'table table-striped']);

**Comment by mpryvkin** [comment]
You should not be using `ajax` and `data` options together unless you use `deferLoading` which you have commented out. Otherwise I don't see a problem with your code, it may be somewhere else.
