### ISSUE TITLE
All checkboxes deselected after table.ajax.reload at the first visit of the page

### ISSUE THREAD

**Issue by flowerpower** [gyrocode/jquery-datatables-checkboxes#78]
I have a DataTable with your jquery-datatables-checkboxes
 and the reload of data every 10 seconds, but when I visit the page of this DataTable the first time and select one or more rows when starts the reload function the selected rows come unselected!! But if I visit another page and then I return on this DataTable page all works very well! Why? How can I solve thi problem?

**I use Bootstrap 3.3.7 and many DataTables javascripts libraries:**
bower_components/datatables.net/js/jquery.dataTables.min.js - **version: 1.10.16** (latest from Bower)
bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js - **DataTables Bootstrap 3 integration**
bower_components/datatables.net-select/js/dataTables.select.min.js - **version 1.2.7** (latest from Bower)
bower_components/**jquery-datatables-checkboxes/js/dataTables.checkboxes.min.js - version 1.2.11**

**Thi is my code loaded (javascript libraries and DataTable definition):**
```
<link href="/Content/bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet"/>
<link href="/Content/bower_components/Ionicons/css/ionicons.min.css" rel="stylesheet"/>
<link href="/Content/dist/css/AdminLTE.min.css" rel="stylesheet"/>
<link href="/Content/dist/css/skins/skin-blue.min.css" rel="stylesheet"/>
 
<!-- DataTables css -->
<link href="/Content/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css" rel="stylesheet"/>
<link href="/Content/bower_components/datatables.net-select-bs/css/select.bootstrap.min.css" rel="stylesheet"/>
<link href="/Content/bower_components/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.css" rel="stylesheet"/>
 
<script src="/Content/bower_components/jquery/dist/jquery.js"></script>
<script src="/Scripts/MyScripts/jquery.validate.min.js"></script>
<script src="/Content/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
<script src="/Content/bower_components/jquery-slimscroll/jquery.slimscroll.min.js"></script>
<script src="/Content/dist/js/adminlte.min.js"></script>
<script src="/Content/dist/js/demo.js"></script>
 
<!-- DataTables javascripts -->
<script src="/Content/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="/Content/bower_components/datatables.net-select/js/dataTables.select.min.js"></script>
<script src="/Content/bower_components/jquery-datatables-checkboxes/js/dataTables.checkboxes.min.js"></script>
<script src="/Content/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
 
<script type="text/javascript" charset="utf-8">
            $(document).ready(function () {
                var table = $('#volumesTable').DataTable({
                    ajax: {
                        type: "POST",
                        url: '<%= ResolveUrl("~/MyWebServices/GetVolumes") %>',
                        contentType: "application/json; charset=utf-8",
                        dataType: "json",
                        dataSrc: "ListOfVolumes"
                    },
                    columns: [
                        { data: 'Request' },
                        { data: 'Matrix' },
                        { data: 'Collocation' },
                        { data: 'Date' },
                        { data: 'Hour' },
                        { data: 'Floor' },
                        { data: 'Request' }
                    ],
                    columnDefs: [
                        {
                            className: "dt-center", "targets": "_all"
                        },
                        {
                            orderable: false, "targets": -1
                        },
                        {
                            targets: -1,
                            render: function (data, type, row, meta) {
                                if (type === "display") {
                                    data = '<div class="checkbox"><input type="checkbox" class="dt-checkboxes"><label></label></div>';
                                }
                                return data;
                            },
                            checkboxes: {
                                selectRow: true,
                                selectAllRender: '<div class="checkbox"><input type="checkbox" class="dt-checkboxes"><label></label></div>'
                            }
                        }
                    ],
                    select: 'multi',
                    order: [[3, 'desc']],                   
                    stateSave: true,                   
                    rowId: 'extn'
                });
 
                setInterval(function () {
                    table.ajax.reload(null, false);
                }, 10000);
});
</script>
```

**Comment by mpryvkin** [comment]
Try using the latest version 1.2.11 and let me know if it works. In that release there was issue #64 corrected that was related to state saving.

**Comment by flowerpower** [comment]
Also with 1.2.11 version there is the problem.
[Here](https://jsfiddle.net/uym5drwh/23/) you can see an example with the use of table.ajax.reload function (reload every 10 seconds). At the first visit of the page the table.ajax.reload function deselects all the selected rows. But if you reload the page or press F5 button all works fine. For the example you can select one or more rows and wait the run of table.ajax.reload function.

**Comment by haromy** [comment]
is it server side right ?
disable `stateSave:true`, set false or remove it.
add `serverSide: true,` in option

this my code where is worked for me. I'm used it on laravel
```javascript
   var tables_output = $('#pending_tables').DataTable({
        'columnDefs': [
            {
                'targets': 0,
                'checkboxes': {
                    'selectRow': true
                },
                'render': function (data, type, full, meta){
                    return '<input type="checkbox" class="dt-checkboxes" name="id[]" value="' + $('<div/>').text(data).html() + '">';
                }
            }
        ],
        'select': {
            'style': 'multi'
        },
        'order': [[8, 'asc']],
        searching: false,
        scrollX: true,
        processing: true,
        serverSide: true,
        ajax: '{!! route('pendinglookup') !!}',
        columns: [
            {data: 'id'},
            {data: 'trans_id'},
            {data: 'acc_nm'},
            {data: 'acc_no'},
            {data: 'bank_cd'},
            {data: 'trans_type'},
            {data: 'amount'},
            {data: 'ref_no'},
            {data: 'created_at'}
        ]
    });

```

**Comment by flowerpower** [comment]
> 
> 
> is it server side right ?
> disable `stateSave:true`, set false or remove it.
> add `serverSide: true,` in option
> 
> this my code where is worked for me. I'm used it on laravel
> 
> ```js
>    var tables_output = $('#pending_tables').DataTable({
>         'columnDefs': [
>             {
>                 'targets': 0,
>                 'checkboxes': {
>                     'selectRow': true
>                 },
>                 'render': function (data, type, full, meta){
>                     return '<input type="checkbox" class="dt-checkboxes" name="id[]" value="' + $('<div/>').text(data).html() + '">';
>                 }
>             }
>         ],
>         'select': {
>             'style': 'multi'
>         },
>         'order': [[8, 'asc']],
>         searching: false,
>         scrollX: true,
>         processing: true,
>         serverSide: true,
>         ajax: '{!! route('pendinglookup') !!}',
>         columns: [
>             {data: 'id'},
>             {data: 'trans_id'},
>             {data: 'acc_nm'},
>             {data: 'acc_no'},
>             {data: 'bank_cd'},
>             {data: 'trans_type'},
>             {data: 'amount'},
>             {data: 'ref_no'},
>             {data: 'created_at'}
>         ]
>     });
> ```

Thanks for your answer, but I don't use the **serverSide** parameter and I don't need to user serverSide. The solution of this bug (I think that is a bug) is this: 
```       
<script type="text/javascript">
            $(document).ready(function(){    
            //Check if the current URL contains '#'
            if(document.URL.indexOf("#")==-1){
                // Set the URL to whatever it was plus "#".
                url = document.URL+"#";
                location = "#";
                //Reload the page
                location.reload(true);
                }
            });
</script>
```
At the first visit of the page I force an auto refresh of the page (one time).
This is the only solution to turn around the bug that I have found.
Any other solution from @mpryvkin ?

**Comment by flowerpower** [comment]
I have solved the problem. The magic tip is to use the rowId option!!
In my example the rowId value is wrong, I need to use a unique json item returned from the ajax call. In my case:
...
rowId: 'extn' --> rowId: 'Collocation'
