### ISSUE TITLE
Problem with selected rows + stateSave + table.ajax.reload + removed data

### ISSUE THREAD

**Issue by flowerpower** [gyrocode/jquery-datatables-checkboxes#79]
This is the problem:
I have a dataTable with some **rows loaded with ajax from database**, I use the **table.ajax.reload** function (for reloading data every 10 seconds) and the **stateSave** (for keep selected rows after every reload of data).
1. **I select 3 rows** and the selected row counter on the table footer correctly say: "**3** rows selected".
2. I remove from database one of the selected rows.
3. The table.ajax.reload function runs and reloads the data on the table and now there are a lower number of rows.
4. Now the remaining visible selected rows is correctly **2** (because one is been removed from database) but the rows counter on the footer of the table count a wrong number! The counter say again "**3** rows selected" !!!

How can I solve this problem?

**Comment by haromy** [comment]
is it server side ajax ?
dont use `stateSave`,
add option `serverSide: true,`

**Comment by flowerpower** [comment]
> 
> 
> is it server side ajax ?
> dont use `stateSave`,
> add option `serverSide: true,`

Hi, I don't use serverSide parameter and I don't need to use it. I think that I found the problem in the **jquery-datatables-checkboxes.js** file (latest version **1.2.11**):
Lines from #832 to #838
```
// Count number of selected rows
var countRows = 0;
for (var cellData in ctx.checkboxes.s.data[colIdx]){
	if (ctx.checkboxes.s.data[colIdx].hasOwnProperty(cellData)) {
		countRows++;
	}
}
```
The count of the selected checkboxes is wrong (creates problems in the case that I have described)
This is my modifications of the javascript:
I have removed the code above and added this:
```
var table = $(dt.table().node()).DataTable();
var rows_selected = table.column(colIdx).checkboxes.selected();
```
And I have modified this code (few lines under the above code) from this:
```
var $output  = $('<span class="select-info"/>');
add($output, 'row', countRows); 
```
To this:
```
var $output  = $('<span class="select-info"/>');
add($output, 'row', rows_selected.length);
```
This solution works for me for all tables in my webapp.
@mpryvkin this solution is correct for you?
Thank you in advance!

**Comment by flowerpower** [comment]
I have solved the problem. The magic tip is to use the rowId option!!
In my example the rowId value is wrong, I need to use a unique json item returned from the ajax call. In my case:
for example:
**rowId: 'Collocation'**
where Collocation is an item of my json.
