### ISSUE TITLE
Selecting One Selects All

### ISSUE THREAD

**Issue by JRascagneres** [gyrocode/jquery-datatables-checkboxes#82]
When I click the checkbox on one of my rows instead of the 'Select All' box showing the '-' it shows the tick. This results in all of the checkboxes being checked when I use the API method. Please help!

**Comment by mpryvkin** [comment]
Can you create an example based on [this jsFiddle](https://jsfiddle.net/gyrocode/snqw56dw/) to demonstrate the problem? 

Also what browser are you using? Do you have unique values in the column containing checkboxes?

**Comment by JRascagneres** [comment]
Wow. Sorry, during testing I changed code and realised they didn't have unique values!
