### ISSUE TITLE
selectRow not working

### ISSUE THREAD

**Issue by Zolak94** [gyrocode/jquery-datatables-checkboxes#87]
This is my columnDefs
```
columnDefs: [
  {
    targets: 0,
    checkboxes: {
      selectRow: true
    }
  }
],
```
And my select is like this 
```
 'select': {
  'style': 'multi'
},
```
But when i click on mine row checkbox is not selected.

**Comment by eazrael** [comment]
Had the same issue.
Cause: Only select.bootstrap4.js included
Solution: Load dataTables.select.js before select.bootstrap4.js.

**Comment by mpryvkin** [comment]
@eazrael thanks for the info, I think that is essentially what happened.
