### ISSUE TITLE
Multiple language support 

### ISSUE THREAD

**Issue by Lb-lea** [gyrocode/jquery-datatables-checkboxes#88]
Hello,
unlike datables.net, the plugin doesn't seem to support other languages than English. 
The messages when rows are selectend is "x rows selected" although the language of the datable is set to an other language....
Maybe the plugin could detect the language of the table or have a parameter to change the default message....

**Comment by mpryvkin** [comment]
Please use [`language.select.rows`](https://datatables.net/reference/option/language.select.rows) option to translate X rows selected. 

Thanks for pointing that out, I will update the documentation.

**Comment by mpryvkin** [comment]
Added [Localization](https://www.gyrocode.com/projects/jquery-datatables-checkboxes/examples/basic/localization/) page.
