### ISSUE TITLE
 table.column is not a function

### ISSUE THREAD

**Issue by gotexis** [gyrocode/jquery-datatables-checkboxes#90]
```javascript
var rows_selected = table.column(0).checkboxes.selected();
```

```
Uncaught TypeError: table.column is not a function
    at <anonymous>:1:27
```

**Comment by mpryvkin** [comment]
Most likely you're using `dataTable()` instead of `DataTable()` to initialize your table. Use `DataTable()` instead, see [API](https://datatables.net/reference/api/) for more information.
