### ISSUE TITLE
Cant make this work with columns defined. 

### ISSUE THREAD

**Issue by z3us94** [gyrocode/jquery-datatables-checkboxes#92]
Hi, 
i have a code where i initialize the table with both column and column defs. With column defs i do that to init this checkboxes thing but it does not work. When i define checkbox with column def to the index 0 it replaces the column 0 that i have defined. below is the code. is there something im doing wrong ?

```
let theTable = $('#xxx').DataTable({
    "searching": false,
    data: [],
    columns: [
      { data: "xxx" },
      { data: "xxx" },
      { data: "xxx" },
      { data: "xxx" },
      { data: "xxx" },
      { data: "xxx" },
      { data: "xxx" },
    ],
    columnDefs: [
      {
        'targets': 0,
        'checkboxes': {
          'selectRow': true
        }
      }
    ],
    select: {
      style: 'os',
      selector: 'td:first-child'
    },
    order: [[1, 'asc']],
  });
```

also i found a solution like this, to define the columns like below.
```
columns: [
      { data: '', defaultContent: '' },
      { data: "xxx" },
      { data: "xxx" },
      { data: "xxx" },
      { data: "xxx" },
      { data: "xxx" },
      { data: "xxx" },
      { data: "xxx" },
    ],
```
but it breaks the way that checkbox working.
thanks in advance

**Comment by wickedsp1d3r** [comment]
Hi,
It seems like the plugin cannot handle this kind of configuration.
So if you would like to use it with a server-side DataTable, you are restricted to use these kind of responses as shown [here](https://datatables.net/examples/data_sources/server_side) (no need to define `columns`).
```
"data": [
  ["One", "Two", "Three"],
  ["One", "Two", "Three"],
  ["One", "Two", "Three"]
]
```
Could the developer confirm this?

**Comment by mpryvkin** [comment]
The only limitation currently is that column containing checkboxes must contain unique data. You cannot use `data: ''` or `data: null` with either [`columns.data`](https://datatables.net/reference/option/columns.data) or [`columnDefs.data`](https://datatables.net/reference/option/column.data) options.

So if you're using the following initialization options, your data with property `id` should contain unique values.
 
**Initialization options:**

```
    columns: [
      { data: "id" },
      { data: "xxx" },
      { data: "xxx" },
      { data: "xxx" },
      { data: "xxx" },
      { data: "xxx" },
      { data: "xxx" },
    ],
    columnDefs: [
      {
        'targets': 0,
        'checkboxes': {
          'selectRow': true
        }
      }
    ],
```

**Sample data:**

```
"data": [
  {"id": 1, "xxx": "One" },
  {"id": 2, "xxx": "Two" },
  {"id": 3, "xxx": "Three" }
]
```
