### ISSUE TITLE
Remove header checkbox clickable in datatables-checkboxes.

### ISSUE THREAD

**Issue by virenbpanchal** [gyrocode/jquery-datatables-checkboxes#93]
Hello,

How to remove checkbox from header of a datatable. I have tried below changes in CSS. Though cursor is not allowed, it still clickable and selects all records.

```
table.dataTable thead th.dt-checkboxes-select-all {
    cursor: not-allowed;
}
table.dataTable thead th.dt-checkboxes-select-all input[type="checkbox"] {
    display: none;
}
```

Thank you very much for all your time and effort you have put for this awesome jquery-datatables-checkboxes. It really helps.

**Comment by mpryvkin** [comment]
Try setting [`columns.checkboxes.selectAll`](https://www.gyrocode.com/projects/jquery-datatables-checkboxes/reference/options/#columns.checkboxes.selectAll) option to `false` to disable “select all” control in the header.

**Comment by virenbpanchal** [comment]
Thanks for your reply. Below solution works as you suggested.

```
//Below prevents click action on select-all checkbox in Header.
$('.dt-checkboxes-select-all').click(false);
```

Also I have make following changes to CSS to disappear Checkbox in header.
```
table.dataTable thead th.dt-checkboxes-select-all {
    cursor: not-allowed;
}
table.dataTable thead th.dt-checkboxes-select-all input[type="checkbox"] {
    display: none;
}
```

**Comment by nickpapoutsis** [comment]
@virenbpanchal That's not the right solution (even though it kinda works).

Just use `columns.checkboxes.selectAll` like this:

```       
 'columnDefs': [
          {
         'targets': 0,
         'checkboxes': {
              selectAll: false
         }
 ]
```

This simply disables the checkbox in the header and doesn't require any CSS or other code to make it work or look good.
