### ISSUE TITLE
How can set name attribute for checkbox

### ISSUE THREAD

**Issue by ZimaSystem** [gyrocode/jquery-datatables-checkboxes#95]
Hello
I need to add name attribute for checkbox.did you have any solution ?
Thank you

**Comment by mpryvkin** [comment]
You can use [`columns.render`](https://datatables.net/reference/option/columns.render) option and define custom HTML markup for your checkbox. Default HTML markup is `<input type="checkbox" class="dt-checkboxes">`. Currently the only requirement for `input` element is to have `dt-checkboxes` class.

See [Awesome Bootstrap Checkbox](https://www.gyrocode.com/projects/jquery-datatables-checkboxes/examples/styling/awesome-bootstrap-checkbox/) for demonstration.
