### ISSUE TITLE
Doesn't show number of selected row in the footer.

### ISSUE THREAD

**Issue by swim89** [gyrocode/jquery-datatables-checkboxes#96]
Hi, I can't see the number of selected row in my datatables.

In my html code I can see only this: 

`<div class="dataTables_info" id="customerTable_info" role="status" aria-live="polite">Showing 1 to 25 of 30 entries</div>`

instead of
`<div class="dataTables_info" id="example_info" role="status" aria-live="polite">Showing 1 to 10 of 57 entries<span class="select-info"><span class="select-item">1 row selected</span></span></div>`

I tried to copy only the code of the table and JS on JSFiddle and try there, but all works, not in my website. 

What I have to looking for?
Thanks

**Comment by vancrypto** [comment]
I have a similar, possibly related issue where the number of rows selected always says 1 no matter how many I select.

**Comment by swim89** [comment]
@vancrypto to solve your problem, you have to fill the checkbox column with unique id.
For example:

`<td>id1</td>`

**Comment by mpryvkin** [comment]
@swim89 Without the code and data, it's really hard to tell what is going on. Can you please share your DataTables initialization code and sample data?

**Comment by vancrypto** [comment]
Thanks @swim89 by adding a unique ID to the checkbox column the number of rows selected is displayed correctly.

**Comment by swim89** [comment]
@mpryvkin if I copy my code on JSFiddle there isn't the problem, it is only on my project :(
