### ISSUE TITLE
Not rendering checkboxes for columns with no data

### ISSUE THREAD

**Issue by jardayn** [gyrocode/jquery-datatables-checkboxes#97]
It would be cool if there was a way to not render checkboxes, if the td tag was empty.

**Comment by mpryvkin** [comment]
It is possible now, please see [this example](https://jsfiddle.net/a79js6mg/). The solution is based on [disabling checkbox on page load](https://www.gyrocode.com/projects/jquery-datatables-checkboxes/examples/api/disable-checkboxes/) example.
