### ISSUE TITLE
data source html faces unexpected checkbox behavour

### ISSUE THREAD

**Issue by gercker** [gyrocode/jquery-datatables-checkboxes#98]
Hi Michael,

my name is Gerhard, cannot get the nice checkbox behaviour with data source HTML. As soon as I remove the ajax option from the DataTable constructor, there is no more undefined checkbox in the header (when only some boxes are checked), and checking one of several unchecked boxes always checks the header box (should be undefined). Please see line 83 in the attached code (basically taken from your website):

[datatable-checkbox.txt](https://github.com/gyrocode/jquery-datatables-checkboxes/files/3363334/datatable-checkbox.txt)

**Comment by mpryvkin** [comment]
One of the limitations of the jQuery DataTables plug-in is that column containing checkboxes must have unique data.

See [Data sources - HTML](https://www.gyrocode.com/projects/jquery-datatables-checkboxes/examples/data-sources/dom/) example where first column contains unique values - `1`, `2`, `3`, etc.
